import type { FormulaFunction } from "./types";
import { generatedFormulaFunctions } from "./formulaFunctionCatalog.generated";
import { profileFormulaFunctions } from "./profileFormulaFunctions";

// Browser-preview mirror of framework-core's native Polars expression surface.
// Native and MCP clients receive this catalog directly from Rust.
const definitions: Array<
  [
    id: string,
    name: string,
    aliases: string[],
    category: string,
    signature: string,
    description: string,
    minimumArguments: number,
    maximumArguments: number
  ]
> = [
  [
    "root.sum_horizontal",
    "sum_horizontal",
    ["row sum"],
    "Horizontal",
    "sum_horizontal([expressions], ignore_nulls=True)",
    "Sum expressions across each row.",
    1,
    64,
  ],
  [
    "root.mean_horizontal",
    "mean_horizontal",
    ["row mean"],
    "Horizontal",
    "mean_horizontal([expressions], ignore_nulls=True)",
    "Average expressions across each row.",
    1,
    64,
  ],
  [
    "root.min_horizontal",
    "min_horizontal",
    ["row minimum"],
    "Horizontal",
    "min_horizontal([expressions])",
    "Find the row-wise minimum.",
    1,
    64,
  ],
  [
    "root.max_horizontal",
    "max_horizontal",
    ["row maximum"],
    "Horizontal",
    "max_horizontal([expressions])",
    "Find the row-wise maximum.",
    1,
    64,
  ],
  [
    "root.coalesce",
    "coalesce",
    ["first non-null"],
    "Nulls",
    "coalesce([expressions])",
    "Return the first non-null expression.",
    1,
    64,
  ],
  [
    "root.sequence",
    "sequence",
    ["range", "number series", "date range", "Excel SEQUENCE"],
    "Generators",
    "sequence(start, stop=None, step=1, periods=None)",
    "Generate numbers or dates up to, but not including, stop. For a date fill, periods=frame.len() makes exactly one date per row.",
    1,
    3,
  ],
  [
    "root.recur",
    "recur",
    ["recurrence", "calculate down rows", "recursive column", "carry forward"],
    "Row order",
    "recur(first, next, restart_by=[columns])",
    "Start a column with one value, then calculate each later row from previous() and the current row.",
    2,
    2,
  ],
  [
    "root.previous",
    "previous",
    ["previous result", "prior result", "row above"],
    "Row order",
    "previous()",
    "Read the result calculated for the preceding row inside recur(...).",
    0,
    0,
  ],
  [
    "root.frame_len",
    "frame.len",
    ["row count", "frame length", "rows", "n_rows", "frame.n_rows"],
    "Generators",
    "frame.len()",
    "Count rows at the current point in this frame's transformation chain.",
    0,
    0,
  ],
  [
    "root.when",
    "when",
    ["conditional"],
    "Conditional",
    "when(condition).then(value).otherwise(value)",
    "Build a Polars conditional expression.",
    1,
    1,
  ],
  [
    "root.date",
    "date",
    ["make date"],
    "Dates",
    "date(year, month, day)",
    "Construct a Date expression.",
    3,
    3,
  ],
  [
    "root.today",
    "today",
    ["current date"],
    "Dates",
    "today()",
    "Today's date, read when the frame is read.",
    0,
    0,
  ],
  [
    "root.now",
    "now",
    ["current time"],
    "Dates",
    "now()",
    "The current date and time, read when the frame is read.",
    0,
    0,
  ],
  [
    "expr.is_between",
    ".is_between",
    ["range", "within"],
    "Comparison",
    '.is_between(lower, upper, closed="both")',
    "Test whether values fall in a range, ends included.",
    2,
    2,
  ],
  [
    "expr.is_in",
    ".is_in",
    ["one of", "member of"],
    "Comparison",
    ".is_in([values])",
    "Test whether values appear in a list.",
    1,
    1,
  ],
  [
    "expr.filter",
    ".filter",
    [
      "sumif",
      "sumifs",
      "countif",
      "countifs",
      "averageif",
      "averageifs",
      "maxifs",
      "minifs",
      "conditional aggregate",
      "where",
    ],
    "Conditional",
    ".filter(predicate)",
    "Keep values whose matching rows meet a condition; chain .sum(), .mean(), or another aggregate.",
    1,
    1,
  ],
  [
    "expr.abs",
    ".abs",
    ["absolute"],
    "Numeric methods",
    ".abs()",
    "Return absolute values.",
    0,
    0,
  ],
  [
    "expr.sign",
    ".sign",
    ["signum"],
    "Numeric methods",
    ".sign()",
    "Return each value's sign.",
    0,
    0,
  ],
  [
    "expr.round",
    ".round",
    ["rounded"],
    "Numeric methods",
    ".round(decimals=0)",
    "Round numeric values.",
    0,
    1,
  ],
  [
    "expr.round_sig_figs",
    ".round_sig_figs",
    ["significant figures"],
    "Numeric methods",
    ".round_sig_figs(digits)",
    "Round to significant figures.",
    1,
    1,
  ],
  [
    "expr.truncate",
    ".truncate",
    ["trunc"],
    "Numeric methods",
    ".truncate(decimals=0)",
    "Truncate numeric values.",
    0,
    1,
  ],
  ["expr.floor", ".floor", [], "Numeric methods", ".floor()", "Round down.", 0, 0],
  ["expr.ceil", ".ceil", ["ceiling"], "Numeric methods", ".ceil()", "Round up.", 0, 0],
  [
    "expr.sqrt",
    ".sqrt",
    ["square root"],
    "Numeric methods",
    ".sqrt()",
    "Compute square roots.",
    0,
    0,
  ],
  [
    "expr.cbrt",
    ".cbrt",
    ["cube root"],
    "Numeric methods",
    ".cbrt()",
    "Compute cube roots.",
    0,
    0,
  ],
  [
    "expr.pow",
    ".pow",
    ["power"],
    "Numeric methods",
    ".pow(exponent)",
    "Raise values to a power.",
    1,
    1,
  ],
  [
    "expr.exp",
    ".exp",
    ["exponential"],
    "Logs",
    ".exp()",
    "Raise e to each value.",
    0,
    0,
  ],
  [
    "expr.log",
    ".log",
    ["ln", "logarithm"],
    "Logs",
    ".log(base=e)",
    "Compute logarithms.",
    0,
    1,
  ],
  [
    "expr.log1p",
    ".log1p",
    ["ln one plus"],
    "Logs",
    ".log1p()",
    "Compute ln(1+x).",
    0,
    0,
  ],
  [
    "expr.clip",
    ".clip",
    ["clamp"],
    "Numeric methods",
    ".clip(lower, upper)",
    "Clip values to bounds.",
    2,
    2,
  ],
  [
    "expr.clip_min",
    ".clip_min",
    ["at least"],
    "Numeric methods",
    ".clip_min(lower)",
    "Clip to a lower bound.",
    1,
    1,
  ],
  [
    "expr.clip_max",
    ".clip_max",
    ["at most"],
    "Numeric methods",
    ".clip_max(upper)",
    "Clip to an upper bound.",
    1,
    1,
  ],
  [
    "expr.floor_div",
    ".floor_div",
    ["floor division"],
    "Numeric methods",
    ".floor_div(divisor)",
    "Floor-divide values.",
    1,
    1,
  ],
  ["expr.sin", ".sin", ["sine"], "Trigonometry", ".sin()", "Compute sine.", 0, 0],
  ["expr.cos", ".cos", ["cosine"], "Trigonometry", ".cos()", "Compute cosine.", 0, 0],
  ["expr.tan", ".tan", ["tangent"], "Trigonometry", ".tan()", "Compute tangent.", 0, 0],
  [
    "expr.cot",
    ".cot",
    ["cotangent"],
    "Trigonometry",
    ".cot()",
    "Compute cotangent.",
    0,
    0,
  ],
  [
    "expr.arcsin",
    ".arcsin",
    ["inverse sine"],
    "Trigonometry",
    ".arcsin()",
    "Compute inverse sine.",
    0,
    0,
  ],
  [
    "expr.arccos",
    ".arccos",
    ["inverse cosine"],
    "Trigonometry",
    ".arccos()",
    "Compute inverse cosine.",
    0,
    0,
  ],
  [
    "expr.arctan",
    ".arctan",
    ["inverse tangent"],
    "Trigonometry",
    ".arctan()",
    "Compute inverse tangent.",
    0,
    0,
  ],
  [
    "expr.arctan2",
    ".arctan2",
    [],
    "Trigonometry",
    ".arctan2(x)",
    "Compute quadrant-aware inverse tangent.",
    1,
    1,
  ],
  [
    "expr.sinh",
    ".sinh",
    [],
    "Trigonometry",
    ".sinh()",
    "Compute hyperbolic sine.",
    0,
    0,
  ],
  [
    "expr.cosh",
    ".cosh",
    [],
    "Trigonometry",
    ".cosh()",
    "Compute hyperbolic cosine.",
    0,
    0,
  ],
  [
    "expr.tanh",
    ".tanh",
    [],
    "Trigonometry",
    ".tanh()",
    "Compute hyperbolic tangent.",
    0,
    0,
  ],
  [
    "expr.arcsinh",
    ".arcsinh",
    [],
    "Trigonometry",
    ".arcsinh()",
    "Compute inverse hyperbolic sine.",
    0,
    0,
  ],
  [
    "expr.arccosh",
    ".arccosh",
    [],
    "Trigonometry",
    ".arccosh()",
    "Compute inverse hyperbolic cosine.",
    0,
    0,
  ],
  [
    "expr.arctanh",
    ".arctanh",
    [],
    "Trigonometry",
    ".arctanh()",
    "Compute inverse hyperbolic tangent.",
    0,
    0,
  ],
  [
    "expr.degrees",
    ".degrees",
    ["to degrees"],
    "Trigonometry",
    ".degrees()",
    "Convert radians to degrees.",
    0,
    0,
  ],
  [
    "expr.radians",
    ".radians",
    ["to radians"],
    "Trigonometry",
    ".radians()",
    "Convert degrees to radians.",
    0,
    0,
  ],
  [
    "expr.is_null",
    ".is_null",
    ["is missing"],
    "Nulls",
    ".is_null()",
    "Test for null values.",
    0,
    0,
  ],
  [
    "expr.is_not_null",
    ".is_not_null",
    ["is present"],
    "Nulls",
    ".is_not_null()",
    "Test for non-null values.",
    0,
    0,
  ],
  [
    "expr.fill_null",
    ".fill_null",
    ["replace null"],
    "Nulls",
    ".fill_null(value)",
    "Replace null values.",
    1,
    1,
  ],
  [
    "expr.shift",
    ".shift",
    ["lag", "lead"],
    "Window",
    ".shift(periods)",
    "Shift values by row position.",
    1,
    1,
  ],
  [
    "expr.over",
    ".over",
    ["window", "partition"],
    "Window",
    ".over([columns])",
    "Evaluate over partition groups.",
    1,
    64,
  ],
  [
    "expr.sum",
    ".sum",
    ["total"],
    "Aggregation",
    ".sum()",
    "Sum a column expression.",
    0,
    0,
  ],
  [
    "expr.mean",
    ".mean",
    ["average"],
    "Aggregation",
    ".mean()",
    "Average a column expression.",
    0,
    0,
  ],
  [
    "expr.min",
    ".min",
    ["minimum"],
    "Aggregation",
    ".min()",
    "Find a column minimum.",
    0,
    0,
  ],
  [
    "expr.max",
    ".max",
    ["maximum"],
    "Aggregation",
    ".max()",
    "Find a column maximum.",
    0,
    0,
  ],
  [
    "expr.count",
    ".count",
    [],
    "Aggregation",
    ".count()",
    "Count non-null values.",
    0,
    0,
  ],
  [
    "expr.len",
    ".len",
    ["length"],
    "Aggregation",
    ".len()",
    "Count values including nulls.",
    0,
    0,
  ],
  [
    "expr.null_count",
    ".null_count",
    [],
    "Aggregation",
    ".null_count()",
    "Count null values.",
    0,
    0,
  ],
  [
    "expr.rolling_mean",
    ".rolling_mean",
    ["moving average"],
    "Rolling",
    ".rolling_mean(window_size, min_periods=1, center=False)",
    "Compute a rolling mean.",
    1,
    1,
  ],
  [
    "expr.rolling_sum",
    ".rolling_sum",
    ["moving sum"],
    "Rolling",
    ".rolling_sum(window_size, min_periods=1, center=False)",
    "Compute a rolling sum.",
    1,
    1,
  ],
  [
    "expr.rolling_min",
    ".rolling_min",
    ["moving minimum"],
    "Rolling",
    ".rolling_min(window_size, min_periods=1, center=False)",
    "Compute a rolling minimum.",
    1,
    1,
  ],
  [
    "expr.rolling_max",
    ".rolling_max",
    ["moving maximum"],
    "Rolling",
    ".rolling_max(window_size, min_periods=1, center=False)",
    "Compute a rolling maximum.",
    1,
    1,
  ],
  [
    "dt.year",
    ".dt.year",
    [],
    "Date namespace",
    ".dt.year()",
    "Extract calendar year.",
    0,
    0,
  ],
  [
    "dt.iso_year",
    ".dt.iso_year",
    [],
    "Date namespace",
    ".dt.iso_year()",
    "Extract ISO year.",
    0,
    0,
  ],
  [
    "dt.quarter",
    ".dt.quarter",
    [],
    "Date namespace",
    ".dt.quarter()",
    "Extract quarter.",
    0,
    0,
  ],
  [
    "dt.month",
    ".dt.month",
    [],
    "Date namespace",
    ".dt.month()",
    "Extract month.",
    0,
    0,
  ],
  [
    "dt.week",
    ".dt.week",
    [],
    "Date namespace",
    ".dt.week()",
    "Extract ISO week.",
    0,
    0,
  ],
  [
    "dt.weekday",
    ".dt.weekday",
    [],
    "Date namespace",
    ".dt.weekday()",
    "Extract weekday.",
    0,
    0,
  ],
  [
    "dt.ordinal_day",
    ".dt.ordinal_day",
    ["day of year"],
    "Date namespace",
    ".dt.ordinal_day()",
    "Extract ordinal day.",
    0,
    0,
  ],
  [
    "dt.is_leap_year",
    ".dt.is_leap_year",
    [],
    "Date namespace",
    ".dt.is_leap_year()",
    "Test for leap years.",
    0,
    0,
  ],
  [
    "dt.days_in_month",
    ".dt.days_in_month",
    [],
    "Date namespace",
    ".dt.days_in_month()",
    "Count days in the month.",
    0,
    0,
  ],
  [
    "dt.date",
    ".dt.date",
    [],
    "Date namespace",
    ".dt.date()",
    "Extract Date from Datetime.",
    0,
    0,
  ],
  [
    "dt.month_start",
    ".dt.month_start",
    [],
    "Date namespace",
    ".dt.month_start()",
    "Move to the month's first day.",
    0,
    0,
  ],
  [
    "dt.month_end",
    ".dt.month_end",
    [],
    "Date namespace",
    ".dt.month_end()",
    "Move to the month's last day.",
    0,
    0,
  ],
  [
    "dt.offset_by",
    ".dt.offset_by",
    ["date offset"],
    "Date namespace",
    ".dt.offset_by(offset)",
    "Offset dates using a Polars duration string.",
    1,
    1,
  ],
  [
    "str.to_uppercase",
    ".str.to_uppercase",
    ["uppercase"],
    "String namespace",
    ".str.to_uppercase()",
    "Convert strings to uppercase.",
    0,
    0,
  ],
  [
    "str.to_lowercase",
    ".str.to_lowercase",
    ["lowercase"],
    "String namespace",
    ".str.to_lowercase()",
    "Convert strings to lowercase.",
    0,
    0,
  ],
  [
    "str.to_date",
    ".str.to_date",
    [
      "ISO date",
      "parse ISO date",
      "text to date",
      "convert text date",
      "datevalue",
      "Excel DATEVALUE (ISO only)",
    ],
    "String namespace",
    ".str.to_date()",
    'Parse strict ISO date text (YYYY-MM-DD). For other formats, normalize the text first; this is the same conversion as .cast("date").',
    0,
    0,
  ],
  [
    "str.contains",
    ".str.contains",
    ["string contains"],
    "String namespace",
    ".str.contains(pattern, strict=True)",
    "Test strings against a pattern.",
    1,
    1,
  ],
];

const dynamicReturnTypes = new Set([
  "root.when",
  "root.coalesce",
  "root.sequence",
  "root.recur",
  "root.previous",
  "expr.fill_null",
  "expr.filter",
  "expr.shift",
  "expr.over",
]);

const handWrittenFormulaFunctions: FormulaFunction[] = definitions.map((definition) => {
  const [
    id,
    name,
    aliases,
    category,
    signature,
    description,
    minimumArguments,
    maximumArguments,
  ] = definition;
  return {
    id,
    name,
    aliases,
    category,
    signature,
    description,
    minimumArguments,
    maximumArguments,
    returnType: returnType(id),
    nullBehavior: nullBehavior(id),
    // The browser preview has no core-provided catalog. Its fallback help
    // remains the visible signature; desktop entries carry argument prose.
    arguments: [],
  };
});

// The full browser-preview catalog: hand-written core methods plus the
// generated Polars expression surface (see formulaFunctionCatalog.generated.ts).
export const previewFormulaFunctions: FormulaFunction[] = [
  ...handWrittenFormulaFunctions, ...profileFormulaFunctions, ...generatedFormulaFunctions,
];

function returnType(id: string): string {
  if (id === "root.frame_len") return "integer";
  if (dynamicReturnTypes.has(id)) return "dynamic";
  if (
    id === "root.date" ||
    id === "root.today" ||
    id === "root.now" ||
    id.startsWith("dt.month_") ||
    id === "dt.date" ||
    id === "dt.offset_by" ||
    id === "str.to_date"
  )
    return "date";
  if (
    id === "expr.is_null" ||
    id === "expr.is_not_null" ||
    id === "expr.is_between" ||
    id === "expr.is_in" ||
    id === "dt.is_leap_year" ||
    id === "str.contains"
  )
    return "boolean";
  if (id.startsWith("str.")) return "string";
  return "number";
}

function nullBehavior(id: string): string {
  if (id === "root.coalesce" || id === "expr.fill_null") return "handles nulls";
  if (id === "expr.is_null" || id === "expr.is_not_null") return "inspects nulls";
  if (id.includes("horizontal")) return "configurable Polars behavior";
  return "native Polars behavior";
}
