// GENERATED FILE — do not edit by hand.
// Regenerate with: python3 tools/generate_expr_bindings.py
//
// Mirrors crates/framework-core/src/generated_expr_bindings.rs's catalog
// frame for the browser-preview formula autocomplete.
import type { FormulaFunction } from "./types";

const generatedDefinitions: Array<
  [
    id: string,
    name: string,
    aliases: string[],
    category: string,
    signature: string,
    description: string,
    minimumArguments: number,
    maximumArguments: number
  ]
> = [
  [
    "arr.arg_max",
    ".arr.arg_max",
    [],
    "Generated array namespace",
    ".arr.arg_max()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "arr.arg_min",
    ".arr.arg_min",
    [],
    "Generated array namespace",
    ".arr.arg_min()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "arr.get",
    ".arr.get",
    [],
    "Generated array namespace",
    ".arr.get(index, null_on_oob)",
    "Get items in every sub-array by index.",
    2,
    2,
  ],
  [
    "arr.head",
    ".arr.head",
    [],
    "Generated array namespace",
    ".arr.head(n, as_array)",
    "Get the head of every subarray",
    2,
    2,
  ],
  [
    "arr.join",
    ".arr.join",
    [],
    "Generated array namespace",
    ".arr.join(separator, ignore_nulls)",
    "Join all string items in a sub-array and place a separator between them. # Error Raise if inner type of array is not `DataType::String`.",
    2,
    2,
  ],
  [
    "arr.len",
    ".arr.len",
    [],
    "Generated array namespace",
    ".arr.len()",
    "Compute the length of every subarray.",
    0,
    0,
  ],
  [
    "arr.max",
    ".arr.max",
    [],
    "Generated array namespace",
    ".arr.max()",
    "Compute the maximum of the items in every subarray.",
    0,
    0,
  ],
  [
    "arr.mean",
    ".arr.mean",
    [],
    "Generated array namespace",
    ".arr.mean()",
    "Compute the mean of the items in every subarray.",
    0,
    0,
  ],
  [
    "arr.median",
    ".arr.median",
    [],
    "Generated array namespace",
    ".arr.median()",
    "Compute the median of the items in every subarray.",
    0,
    0,
  ],
  [
    "arr.min",
    ".arr.min",
    [],
    "Generated array namespace",
    ".arr.min()",
    "Compute the minimum of the items in every subarray.",
    0,
    0,
  ],
  [
    "arr.shift",
    ".arr.shift",
    [],
    "Generated array namespace",
    ".arr.shift(n)",
    "Shift every sub-array.",
    1,
    1,
  ],
  [
    "arr.slice",
    ".arr.slice",
    [],
    "Generated array namespace",
    ".arr.slice(offset, length, as_array)",
    "Slice every subarray.",
    3,
    3,
  ],
  [
    "arr.std",
    ".arr.std",
    [],
    "Generated array namespace",
    ".arr.std(ddof)",
    "Compute the std of the items in every subarray.",
    1,
    1,
  ],
  [
    "arr.sum",
    ".arr.sum",
    [],
    "Generated array namespace",
    ".arr.sum()",
    "Compute the sum of the items in every subarray.",
    0,
    0,
  ],
  [
    "arr.tail",
    ".arr.tail",
    [],
    "Generated array namespace",
    ".arr.tail(n, as_array)",
    "Get the tail of every subarray",
    2,
    2,
  ],
  [
    "arr.to_list",
    ".arr.to_list",
    [],
    "Generated array namespace",
    ".arr.to_list()",
    "Cast the Array column to List column with the same inner data type.",
    0,
    0,
  ],
  [
    "arr.var",
    ".arr.var",
    [],
    "Generated array namespace",
    ".arr.var(ddof)",
    "Compute the var of the items in every subarray.",
    1,
    1,
  ],
  [
    "cat.ends_with",
    ".cat.ends_with",
    [],
    "Generated categorical namespace",
    ".cat.ends_with(suffix)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "cat.get_categories",
    ".cat.get_categories",
    [],
    "Generated categorical namespace",
    ".cat.get_categories()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "cat.len_bytes",
    ".cat.len_bytes",
    [],
    "Generated categorical namespace",
    ".cat.len_bytes()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "cat.len_chars",
    ".cat.len_chars",
    [],
    "Generated categorical namespace",
    ".cat.len_chars()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "cat.physical",
    ".cat.physical",
    [],
    "Generated categorical namespace",
    ".cat.physical()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "cat.slice",
    ".cat.slice",
    [],
    "Generated categorical namespace",
    ".cat.slice(offset, length?)",
    "See Polars documentation.",
    1,
    2,
  ],
  [
    "cat.starts_with",
    ".cat.starts_with",
    [],
    "Generated categorical namespace",
    ".cat.starts_with(prefix)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "dt.base_utc_offset",
    ".dt.base_utc_offset",
    [],
    "Generated date namespace",
    ".dt.base_utc_offset()",
    "Get the base offset from UTC.",
    0,
    0,
  ],
  [
    "dt.century",
    ".dt.century",
    [],
    "Generated date namespace",
    ".dt.century()",
    "Get the century of a Date/Datetime",
    0,
    0,
  ],
  [
    "dt.datetime",
    ".dt.datetime",
    [],
    "Generated date namespace",
    ".dt.datetime()",
    "Get the (local) datetime of a Datetime.",
    0,
    0,
  ],
  [
    "dt.day",
    ".dt.day",
    [],
    "Generated date namespace",
    ".dt.day()",
    "Get the month of a Date/Datetime.",
    0,
    0,
  ],
  [
    "dt.dst_offset",
    ".dt.dst_offset",
    [],
    "Generated date namespace",
    ".dt.dst_offset()",
    "Get the additional offset from UTC currently in effect (usually due to daylight saving time).",
    0,
    0,
  ],
  [
    "dt.hour",
    ".dt.hour",
    [],
    "Generated date namespace",
    ".dt.hour()",
    "Get the hour of a Datetime/Time64.",
    0,
    0,
  ],
  [
    "dt.microsecond",
    ".dt.microsecond",
    [],
    "Generated date namespace",
    ".dt.microsecond()",
    "Get the microsecond of a Time64 (scaled from nanosecs).",
    0,
    0,
  ],
  [
    "dt.millennium",
    ".dt.millennium",
    [],
    "Generated date namespace",
    ".dt.millennium()",
    "Get the millennium of a Date/Datetime",
    0,
    0,
  ],
  [
    "dt.millisecond",
    ".dt.millisecond",
    [],
    "Generated date namespace",
    ".dt.millisecond()",
    "Get the millisecond of a Time64 (scaled from nanosecs).",
    0,
    0,
  ],
  [
    "dt.minute",
    ".dt.minute",
    [],
    "Generated date namespace",
    ".dt.minute()",
    "Get the minute of a Datetime/Time64.",
    0,
    0,
  ],
  [
    "dt.nanosecond",
    ".dt.nanosecond",
    [],
    "Generated date namespace",
    ".dt.nanosecond()",
    "Get the nanosecond part of a Time64.",
    0,
    0,
  ],
  [
    "dt.replace",
    ".dt.replace",
    [],
    "Generated date namespace",
    ".dt.replace(year, month, day, hour, minute, second, microsecond, ambiguous)",
    "Replace the time units of a value",
    8,
    8,
  ],
  [
    "dt.round",
    ".dt.round",
    [],
    "Generated date namespace",
    ".dt.round(every)",
    "Round the Datetime/Date range into buckets.",
    1,
    1,
  ],
  [
    "dt.second",
    ".dt.second",
    [],
    "Generated date namespace",
    ".dt.second()",
    "Get the second of a Datetime/Time64.",
    0,
    0,
  ],
  [
    "dt.time",
    ".dt.time",
    [],
    "Generated date namespace",
    ".dt.time()",
    "Get the (local) time of a Date/Datetime/Time.",
    0,
    0,
  ],
  [
    "dt.total_days",
    ".dt.total_days",
    [],
    "Generated date namespace",
    ".dt.total_days(fractional)",
    "Express a Duration in terms of its total number of integer days.",
    1,
    1,
  ],
  [
    "dt.total_hours",
    ".dt.total_hours",
    [],
    "Generated date namespace",
    ".dt.total_hours(fractional)",
    "Express a Duration in terms of its total number of integer hours.",
    1,
    1,
  ],
  [
    "dt.total_microseconds",
    ".dt.total_microseconds",
    [],
    "Generated date namespace",
    ".dt.total_microseconds(fractional)",
    "Express a Duration in terms of its total number of microseconds.",
    1,
    1,
  ],
  [
    "dt.total_milliseconds",
    ".dt.total_milliseconds",
    [],
    "Generated date namespace",
    ".dt.total_milliseconds(fractional)",
    "Express a Duration in terms of its total number of milliseconds.",
    1,
    1,
  ],
  [
    "dt.total_minutes",
    ".dt.total_minutes",
    [],
    "Generated date namespace",
    ".dt.total_minutes(fractional)",
    "Express a Duration in terms of its total number of integer minutes.",
    1,
    1,
  ],
  [
    "dt.total_nanoseconds",
    ".dt.total_nanoseconds",
    [],
    "Generated date namespace",
    ".dt.total_nanoseconds(fractional)",
    "Express a Duration in terms of its total number of nanoseconds.",
    1,
    1,
  ],
  [
    "dt.total_seconds",
    ".dt.total_seconds",
    [],
    "Generated date namespace",
    ".dt.total_seconds(fractional)",
    "Express a Duration in terms of its total number of integer seconds.",
    1,
    1,
  ],
  [
    "dt.truncate",
    ".dt.truncate",
    [],
    "Generated date namespace",
    ".dt.truncate(every)",
    "Truncate the Datetime/Date range into buckets.",
    1,
    1,
  ],
  [
    "expr.agg_groups",
    ".agg_groups",
    [],
    "Generated expression methods",
    ".agg_groups()",
    "Get the group indexes of the group by operation.",
    0,
    0,
  ],
  [
    "expr.all",
    ".all",
    [],
    "Generated expression methods",
    ".all(ignore_nulls)",
    "Returns whether all values in the column are `true`.  If `ignore_nulls` is `False`, [Kleene logic] is used to deal with nulls: if the column contains any null values and no `false` values, the output is null.  [Kleene lo",
    1,
    1,
  ],
  [
    "expr.any",
    ".any",
    [],
    "Generated expression methods",
    ".any(ignore_nulls)",
    "Returns whether any of the values in the column are `true`.  If `ignore_nulls` is `False`, [Kleene logic] is used to deal with nulls: if the column contains any null values and no `true` values, the output is null.  [Kle",
    1,
    1,
  ],
  [
    "expr.approx_n_unique",
    ".approx_n_unique",
    [],
    "Generated expression methods",
    ".approx_n_unique()",
    "Get the approximate count of unique values.",
    0,
    0,
  ],
  [
    "expr.arg_max",
    ".arg_max",
    [],
    "Generated expression methods",
    ".arg_max()",
    "Get the index value that has the maximum value.",
    0,
    0,
  ],
  [
    "expr.arg_min",
    ".arg_min",
    [],
    "Generated expression methods",
    ".arg_min()",
    "Get the index value that has the minimum value.",
    0,
    0,
  ],
  [
    "expr.arg_sort",
    ".arg_sort",
    [],
    "Generated expression methods",
    ".arg_sort(descending, nulls_last)",
    "Get the index values that would sort this expression.",
    2,
    2,
  ],
  [
    "expr.arg_unique",
    ".arg_unique",
    [],
    "Generated expression methods",
    ".arg_unique()",
    "Get the first index of unique values of this expression.",
    0,
    0,
  ],
  [
    "expr.bitwise_and",
    ".bitwise_and",
    [],
    "Generated expression methods",
    ".bitwise_and()",
    "Perform an aggregation of bitwise ANDs",
    0,
    0,
  ],
  [
    "expr.bitwise_count_ones",
    ".bitwise_count_ones",
    [],
    "Generated expression methods",
    ".bitwise_count_ones()",
    "Evaluate the number of set bits.",
    0,
    0,
  ],
  [
    "expr.bitwise_count_zeros",
    ".bitwise_count_zeros",
    [],
    "Generated expression methods",
    ".bitwise_count_zeros()",
    "Evaluate the number of unset bits.",
    0,
    0,
  ],
  [
    "expr.bitwise_leading_ones",
    ".bitwise_leading_ones",
    [],
    "Generated expression methods",
    ".bitwise_leading_ones()",
    "Evaluate the number most-significant set bits before seeing an unset bit.",
    0,
    0,
  ],
  [
    "expr.bitwise_leading_zeros",
    ".bitwise_leading_zeros",
    [],
    "Generated expression methods",
    ".bitwise_leading_zeros()",
    "Evaluate the number most-significant unset bits before seeing an set bit.",
    0,
    0,
  ],
  [
    "expr.bitwise_or",
    ".bitwise_or",
    [],
    "Generated expression methods",
    ".bitwise_or()",
    "Perform an aggregation of bitwise ORs",
    0,
    0,
  ],
  [
    "expr.bitwise_trailing_ones",
    ".bitwise_trailing_ones",
    [],
    "Generated expression methods",
    ".bitwise_trailing_ones()",
    "Evaluate the number least-significant set bits before seeing an unset bit.",
    0,
    0,
  ],
  [
    "expr.bitwise_trailing_zeros",
    ".bitwise_trailing_zeros",
    [],
    "Generated expression methods",
    ".bitwise_trailing_zeros()",
    "Evaluate the number least-significant unset bits before seeing an set bit.",
    0,
    0,
  ],
  [
    "expr.bitwise_xor",
    ".bitwise_xor",
    [],
    "Generated expression methods",
    ".bitwise_xor()",
    "Perform an aggregation of bitwise XORs",
    0,
    0,
  ],
  [
    "expr.bottom_k",
    ".bottom_k",
    [],
    "Generated expression methods",
    ".bottom_k(k)",
    "Returns the `k` smallest elements.  This has time complexity `O(n + k log(n))`.",
    1,
    1,
  ],
  [
    "expr.cum_count",
    ".cum_count",
    [],
    "Generated expression methods",
    ".cum_count(reverse)",
    "Cumulatively count values from 0 to len.",
    1,
    1,
  ],
  [
    "expr.cum_max",
    ".cum_max",
    [],
    "Generated expression methods",
    ".cum_max(reverse)",
    "Get an array with the cumulative max computed at every element.",
    1,
    1,
  ],
  [
    "expr.cum_min",
    ".cum_min",
    [],
    "Generated expression methods",
    ".cum_min(reverse)",
    "Get an array with the cumulative min computed at every element.",
    1,
    1,
  ],
  [
    "expr.cum_prod",
    ".cum_prod",
    [],
    "Generated expression methods",
    ".cum_prod(reverse)",
    "Get an array with the cumulative product computed at every element.",
    1,
    1,
  ],
  [
    "expr.cum_sum",
    ".cum_sum",
    [],
    "Generated expression methods",
    ".cum_sum(reverse)",
    "Get an array with the cumulative sum computed at every element.",
    1,
    1,
  ],
  [
    "expr.cumulative_eval",
    ".cumulative_eval",
    [],
    "Generated expression methods",
    ".cumulative_eval(evaluation, min_samples)",
    "Cumulatively count values from 0 to len.",
    2,
    2,
  ],
  [
    "expr.drop_nans",
    ".drop_nans",
    [],
    "Generated expression methods",
    ".drop_nans()",
    "Drop NaN values.",
    0,
    0,
  ],
  [
    "expr.drop_nulls",
    ".drop_nulls",
    [],
    "Generated expression methods",
    ".drop_nulls()",
    "Drop null values.",
    0,
    0,
  ],
  [
    "expr.entropy",
    ".entropy",
    [],
    "Generated expression methods",
    ".entropy(base, normalize)",
    "Compute the entropy as `-sum(pk * log(pk))`. where `pk` are discrete probabilities.",
    2,
    2,
  ],
  [
    "expr.extend_constant",
    ".extend_constant",
    [],
    "Generated expression methods",
    ".extend_constant(value, n)",
    "See Polars documentation.",
    2,
    2,
  ],
  [
    "expr.first",
    ".first",
    [],
    "Generated expression methods",
    ".first()",
    "Get the first value in the group.",
    0,
    0,
  ],
  [
    "expr.first_non_null",
    ".first_non_null",
    [],
    "Generated expression methods",
    ".first_non_null()",
    "Get the first non-nullvalue in the group.",
    0,
    0,
  ],
  [
    "expr.gather_every",
    ".gather_every",
    [],
    "Generated expression methods",
    ".gather_every(n, offset)",
    "See Polars documentation.",
    2,
    2,
  ],
  [
    "expr.has_nulls",
    ".has_nulls",
    [],
    "Generated expression methods",
    ".has_nulls()",
    "Returns whether the column contains one or more null values.",
    0,
    0,
  ],
  [
    "expr.hash",
    ".hash",
    [],
    "Generated expression methods",
    ".hash(k0, k1, k2, k3)",
    "Compute the hash of every element.",
    4,
    4,
  ],
  [
    "expr.head",
    ".head",
    [],
    "Generated expression methods",
    ".head(length?)",
    "Get the first `n` elements of the Expr result.",
    0,
    1,
  ],
  [
    "expr.hist",
    ".hist",
    [],
    "Generated expression methods",
    ".hist(bins?, bin_count?, include_category, include_breakpoint)",
    "Compute the histogram of a dataset.",
    2,
    4,
  ],
  [
    "expr.implode",
    ".implode",
    [],
    "Generated expression methods",
    ".implode(maintain_order)",
    "Implode into a list scalar.",
    1,
    1,
  ],
  [
    "expr.interpolate_by",
    ".interpolate_by",
    [],
    "Generated expression methods",
    ".interpolate_by(by)",
    "Interpolate intermediate values. Nulls at the beginning and end of the series remain null. The `by` column provides the x-coordinates for interpolation and must not contain nulls.",
    1,
    1,
  ],
  [
    "expr.is_duplicated",
    ".is_duplicated",
    [],
    "Generated expression methods",
    ".is_duplicated()",
    "Get a mask of duplicated values.",
    0,
    0,
  ],
  [
    "expr.is_empty",
    ".is_empty",
    [],
    "Generated expression methods",
    ".is_empty(ignore_nulls)",
    "Returns whether this column is empty.  If `ignore_nulls` is True, the column is also considered empty if it only consists of nulls.",
    1,
    1,
  ],
  [
    "expr.is_finite",
    ".is_finite",
    [],
    "Generated expression methods",
    ".is_finite()",
    "Get mask of finite values if dtype is Float.",
    0,
    0,
  ],
  [
    "expr.is_first_distinct",
    ".is_first_distinct",
    [],
    "Generated expression methods",
    ".is_first_distinct()",
    "Get a mask of the first unique value.",
    0,
    0,
  ],
  [
    "expr.is_infinite",
    ".is_infinite",
    [],
    "Generated expression methods",
    ".is_infinite()",
    "Get mask of infinite values if dtype is Float.",
    0,
    0,
  ],
  [
    "expr.is_last_distinct",
    ".is_last_distinct",
    [],
    "Generated expression methods",
    ".is_last_distinct()",
    "Get a mask of the last unique value.",
    0,
    0,
  ],
  [
    "expr.is_nan",
    ".is_nan",
    [],
    "Generated expression methods",
    ".is_nan()",
    "Get mask of NaN values if dtype is Float.",
    0,
    0,
  ],
  [
    "expr.is_not_nan",
    ".is_not_nan",
    [],
    "Generated expression methods",
    ".is_not_nan()",
    "Get inverse mask of NaN values if dtype is Float.",
    0,
    0,
  ],
  [
    "expr.is_sorted",
    ".is_sorted",
    [],
    "Generated expression methods",
    ".is_sorted(descending?, nulls_last?)",
    "See Polars documentation.",
    0,
    2,
  ],
  [
    "expr.is_unique",
    ".is_unique",
    [],
    "Generated expression methods",
    ".is_unique()",
    "Get a mask of unique values.",
    0,
    0,
  ],
  [
    "expr.item",
    ".item",
    [],
    "Generated expression methods",
    ".item(allow_empty)",
    "Get the single value in the group. If there are multiple values, an error is returned.",
    1,
    1,
  ],
  [
    "expr.kurtosis",
    ".kurtosis",
    [],
    "Generated expression methods",
    ".kurtosis(fisher, bias)",
    "Compute the kurtosis (Fisher or Pearson).  Kurtosis is the fourth central moment divided by the square of the variance. If Fisher's definition is used, then 3.0 is subtracted from the result to give 0.0 for a normal dist",
    2,
    2,
  ],
  [
    "expr.last",
    ".last",
    [],
    "Generated expression methods",
    ".last()",
    "Get the last value in the group.",
    0,
    0,
  ],
  [
    "expr.last_non_null",
    ".last_non_null",
    [],
    "Generated expression methods",
    ".last_non_null()",
    "Get the last non-null value in the group.",
    0,
    0,
  ],
  [
    "expr.lower_bound",
    ".lower_bound",
    [],
    "Generated expression methods",
    ".lower_bound()",
    "Get minimal value that could be hold by this dtype.",
    0,
    0,
  ],
  [
    "expr.max_by",
    ".max_by",
    [],
    "Generated expression methods",
    ".max_by(by)",
    "Get maximum value, ordered by another expression.",
    1,
    1,
  ],
  [
    "expr.median",
    ".median",
    [],
    "Generated expression methods",
    ".median()",
    "Reduce groups to the median value.",
    0,
    0,
  ],
  [
    "expr.min_by",
    ".min_by",
    [],
    "Generated expression methods",
    ".min_by(by)",
    "Get minimum value, ordered by another expression.",
    1,
    1,
  ],
  [
    "expr.mode",
    ".mode",
    [],
    "Generated expression methods",
    ".mode(maintain_order)",
    "Compute the mode(s) of this column. This is the most occurring value.",
    1,
    1,
  ],
  [
    "expr.n_unique",
    ".n_unique",
    [],
    "Generated expression methods",
    ".n_unique()",
    "Get the number of unique values in the groups.",
    0,
    0,
  ],
  [
    "expr.nan_max",
    ".nan_max",
    [],
    "Generated expression methods",
    ".nan_max()",
    "Reduce groups to maximum value.",
    0,
    0,
  ],
  [
    "expr.nan_min",
    ".nan_min",
    [],
    "Generated expression methods",
    ".nan_min()",
    "Reduce groups to minimal value.",
    0,
    0,
  ],
  [
    "expr.not",
    ".not",
    [],
    "Generated expression methods",
    ".not()",
    "Negate `Expr`.",
    0,
    0,
  ],
  [
    "expr.pct_change",
    ".pct_change",
    [],
    "Generated expression methods",
    ".pct_change(n)",
    "Computes percentage change between values.",
    1,
    1,
  ],
  [
    "expr.peak_max",
    ".peak_max",
    [],
    "Generated expression methods",
    ".peak_max()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "expr.peak_min",
    ".peak_min",
    [],
    "Generated expression methods",
    ".peak_min()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "expr.product",
    ".product",
    [],
    "Generated expression methods",
    ".product()",
    "Get the product aggregation of an expression.",
    0,
    0,
  ],
  [
    "expr.rechunk",
    ".rechunk",
    [],
    "Generated expression methods",
    ".rechunk()",
    "Collect all chunks into a single chunk before continuing.",
    0,
    0,
  ],
  [
    "expr.reverse",
    ".reverse",
    [],
    "Generated expression methods",
    ".reverse()",
    "Reverse column",
    0,
    0,
  ],
  [
    "expr.rle",
    ".rle",
    [],
    "Generated expression methods",
    ".rle()",
    "Get the lengths of runs of identical values.",
    0,
    0,
  ],
  [
    "expr.rle_id",
    ".rle_id",
    [],
    "Generated expression methods",
    ".rle_id()",
    "Similar to `rle`, but maps values to run IDs.",
    0,
    0,
  ],
  [
    "expr.sample_frac",
    ".sample_frac",
    [],
    "Generated expression methods",
    ".sample_frac(frac, with_replacement, shuffle?, seed?)",
    "See Polars documentation.",
    2,
    4,
  ],
  [
    "expr.sample_n",
    ".sample_n",
    [],
    "Generated expression methods",
    ".sample_n(n, with_replacement, shuffle?, seed?)",
    "See Polars documentation.",
    2,
    4,
  ],
  [
    "expr.shuffle",
    ".shuffle",
    [],
    "Generated expression methods",
    ".shuffle(seed?)",
    "See Polars documentation.",
    0,
    1,
  ],
  [
    "expr.skew",
    ".skew",
    [],
    "Generated expression methods",
    ".skew(bias)",
    "Compute the sample skewness of a data set.  For normally distributed data, the skewness should be about zero. For uni-modal continuous distributions, a skewness value greater than zero means that there is more weight in ",
    1,
    1,
  ],
  [
    "expr.std",
    ".std",
    [],
    "Generated expression methods",
    ".std(ddof)",
    "Standard deviation of the values of the Series.",
    1,
    1,
  ],
  [
    "expr.tail",
    ".tail",
    [],
    "Generated expression methods",
    ".tail(length?)",
    "Get the last `n` elements of the Expr result.",
    0,
    1,
  ],
  [
    "expr.to_physical",
    ".to_physical",
    [],
    "Generated expression methods",
    ".to_physical()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "expr.top_k",
    ".top_k",
    [],
    "Generated expression methods",
    ".top_k(k)",
    "Returns the `k` largest elements.  This has time complexity `O(n + k log(n))`.",
    1,
    1,
  ],
  [
    "expr.true_div",
    ".true_div",
    [],
    "Generated expression methods",
    ".true_div(rhs)",
    "True divide `self` by `rhs`",
    1,
    1,
  ],
  [
    "expr.unique",
    ".unique",
    [],
    "Generated expression methods",
    ".unique()",
    "Get unique values of this expression.",
    0,
    0,
  ],
  [
    "expr.unique_counts",
    ".unique_counts",
    [],
    "Generated expression methods",
    ".unique_counts()",
    "Returns a count of the unique values in the order of appearance. This method differs from [`Expr::value_counts`] in that it does not return the values, only the counts and might be faster.",
    0,
    0,
  ],
  [
    "expr.unique_stable",
    ".unique_stable",
    [],
    "Generated expression methods",
    ".unique_stable()",
    "Get unique values of this expression, while maintaining order. This requires more work than [`Expr::unique`].",
    0,
    0,
  ],
  [
    "expr.upper_bound",
    ".upper_bound",
    [],
    "Generated expression methods",
    ".upper_bound()",
    "Get maximal value that could be hold by this dtype.",
    0,
    0,
  ],
  [
    "expr.var",
    ".var",
    [],
    "Generated expression methods",
    ".var(ddof)",
    "Variance of the values of the Series.",
    1,
    1,
  ],
  [
    "list.arg_max",
    ".list.arg_max",
    [],
    "Generated list namespace",
    ".list.arg_max()",
    "Return the index of the maximum value of every sublist",
    0,
    0,
  ],
  [
    "list.arg_min",
    ".list.arg_min",
    [],
    "Generated list namespace",
    ".list.arg_min()",
    "Return the index of the minimal value of every sublist",
    0,
    0,
  ],
  [
    "list.drop_nulls",
    ".list.drop_nulls",
    [],
    "Generated list namespace",
    ".list.drop_nulls()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "list.first",
    ".list.first",
    [],
    "Generated list namespace",
    ".list.first()",
    "Get first item of every sublist.",
    0,
    0,
  ],
  [
    "list.gather",
    ".list.gather",
    [],
    "Generated list namespace",
    ".list.gather(index, null_on_oob)",
    "Get items in every sublist by multiple indexes.  # Arguments - `null_on_oob`: Return a null when an index is out of bounds. This behavior is more expensive than defaulting to returning an `Error`.",
    2,
    2,
  ],
  [
    "list.gather_every",
    ".list.gather_every",
    [],
    "Generated list namespace",
    ".list.gather_every(n, offset)",
    "See Polars documentation.",
    2,
    2,
  ],
  [
    "list.get",
    ".list.get",
    [],
    "Generated list namespace",
    ".list.get(index, null_on_oob)",
    "Get items in every sublist by index.",
    2,
    2,
  ],
  [
    "list.head",
    ".list.head",
    [],
    "Generated list namespace",
    ".list.head(n)",
    "Get the head of every sublist",
    1,
    1,
  ],
  [
    "list.join",
    ".list.join",
    [],
    "Generated list namespace",
    ".list.join(separator, ignore_nulls)",
    "Join all string items in a sublist and place a separator between them. # Error This errors if inner type of list `!= DataType::String`.",
    2,
    2,
  ],
  [
    "list.last",
    ".list.last",
    [],
    "Generated list namespace",
    ".list.last()",
    "Get last item of every sublist.",
    0,
    0,
  ],
  [
    "list.len",
    ".list.len",
    [],
    "Generated list namespace",
    ".list.len()",
    "Return the number of elements in each list.  Null values are treated like regular elements in this context.",
    0,
    0,
  ],
  [
    "list.max",
    ".list.max",
    [],
    "Generated list namespace",
    ".list.max()",
    "Compute the maximum of the items in every sublist.",
    0,
    0,
  ],
  [
    "list.mean",
    ".list.mean",
    [],
    "Generated list namespace",
    ".list.mean()",
    "Compute the mean of every sublist and return a `Series` of dtype `Float64`",
    0,
    0,
  ],
  [
    "list.median",
    ".list.median",
    [],
    "Generated list namespace",
    ".list.median()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "list.min",
    ".list.min",
    [],
    "Generated list namespace",
    ".list.min()",
    "Compute the minimum of the items in every sublist.",
    0,
    0,
  ],
  [
    "list.sample_fraction",
    ".list.sample_fraction",
    [],
    "Generated list namespace",
    ".list.sample_fraction(fraction, with_replacement, shuffle?, seed?)",
    "See Polars documentation.",
    2,
    4,
  ],
  [
    "list.sample_n",
    ".list.sample_n",
    [],
    "Generated list namespace",
    ".list.sample_n(n, with_replacement, shuffle?, seed?)",
    "See Polars documentation.",
    2,
    4,
  ],
  [
    "list.shift",
    ".list.shift",
    [],
    "Generated list namespace",
    ".list.shift(periods)",
    "Shift every sublist.",
    1,
    1,
  ],
  [
    "list.slice",
    ".list.slice",
    [],
    "Generated list namespace",
    ".list.slice(offset, length)",
    "Slice every sublist.",
    2,
    2,
  ],
  [
    "list.std",
    ".list.std",
    [],
    "Generated list namespace",
    ".list.std(ddof)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "list.sum",
    ".list.sum",
    [],
    "Generated list namespace",
    ".list.sum()",
    "Compute the sum the items in every sublist.",
    0,
    0,
  ],
  [
    "list.tail",
    ".list.tail",
    [],
    "Generated list namespace",
    ".list.tail(n)",
    "Get the tail of every sublist",
    1,
    1,
  ],
  [
    "list.to_array",
    ".list.to_array",
    [],
    "Generated list namespace",
    ".list.to_array(width)",
    "Convert a List column into an Array column with the same inner data type.",
    1,
    1,
  ],
  [
    "list.var",
    ".list.var",
    [],
    "Generated list namespace",
    ".list.var(ddof)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "root.cov",
    "cov",
    [],
    "Generated root functions",
    "cov(a, b, ddof)",
    "Compute the covariance between two columns.",
    3,
    3,
  ],
  [
    "root.pearson_corr",
    "pearson_corr",
    [],
    "Generated root functions",
    "pearson_corr(a, b)",
    "Compute the pearson correlation between two columns.",
    2,
    2,
  ],
  [
    "root.spearman_rank_corr",
    "spearman_rank_corr",
    [],
    "Generated root functions",
    "spearman_rank_corr(a, b, propagate_nans)",
    "Compute the spearman rank correlation between two columns. Missing data will be excluded from the computation. # Arguments * propagate_nans If `true` any `NaN` encountered will lead to `NaN` in the output. If to `false` ",
    3,
    3,
  ],
  [
    "str.base64_decode",
    ".str.base64_decode",
    [],
    "Generated string namespace",
    ".str.base64_decode(strict)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "str.base64_encode",
    ".str.base64_encode",
    [],
    "Generated string namespace",
    ".str.base64_encode()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "str.contains_any",
    ".str.contains_any",
    [],
    "Generated string namespace",
    ".str.contains_any(patterns, ascii_case_insensitive)",
    "Uses aho-corasick to find many patterns.  # Arguments - `patterns`: an expression that evaluates to a String column - `ascii_case_insensitive`: Enable ASCII-aware case insensitive matching. When this option is enabled, s",
    2,
    2,
  ],
  [
    "str.contains_literal",
    ".str.contains_literal",
    [],
    "Generated string namespace",
    ".str.contains_literal(pat)",
    "Check if a string value contains a literal substring.",
    1,
    1,
  ],
  [
    "str.count_matches",
    ".str.count_matches",
    [],
    "Generated string namespace",
    ".str.count_matches(pat, literal)",
    "Count all successive non-overlapping regex matches.",
    2,
    2,
  ],
  [
    "str.ends_with",
    ".str.ends_with",
    [],
    "Generated string namespace",
    ".str.ends_with(sub)",
    "Check if a string value ends with the `sub` string.",
    1,
    1,
  ],
  [
    "str.escape_regex",
    ".str.escape_regex",
    [],
    "Generated string namespace",
    ".str.escape_regex()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "str.extract",
    ".str.extract",
    [],
    "Generated string namespace",
    ".str.extract(pat, group_index)",
    "Extract a regex pattern from the a string value. If `group_index` is out of bounds, null is returned.",
    2,
    2,
  ],
  [
    "str.extract_all",
    ".str.extract_all",
    [],
    "Generated string namespace",
    ".str.extract_all(pat)",
    "Extract each successive non-overlapping match in an individual string as an array",
    1,
    1,
  ],
  [
    "str.extract_many",
    ".str.extract_many",
    [],
    "Generated string namespace",
    ".str.extract_many(patterns, ascii_case_insensitive, overlapping, leftmost)",
    "Uses aho-corasick to replace many patterns. # Arguments - `patterns`: an expression that evaluates to a String column - `ascii_case_insensitive`: Enable ASCII-aware case-insensitive matching. When this option is enabled,",
    4,
    4,
  ],
  [
    "str.find",
    ".str.find",
    [],
    "Generated string namespace",
    ".str.find(pat, strict)",
    "Find the index of a substring defined by a regular expressions within another string value.",
    2,
    2,
  ],
  [
    "str.find_literal",
    ".str.find_literal",
    [],
    "Generated string namespace",
    ".str.find_literal(pat)",
    "Find the index of a literal substring within another string value.",
    1,
    1,
  ],
  [
    "str.find_many",
    ".str.find_many",
    [],
    "Generated string namespace",
    ".str.find_many(patterns, ascii_case_insensitive, overlapping, leftmost)",
    "Uses aho-corasick to find many patterns. # Arguments - `patterns`: an expression that evaluates to a String column - `ascii_case_insensitive`: Enable ASCII-aware case-insensitive matching. When this option is enabled, se",
    4,
    4,
  ],
  [
    "str.head",
    ".str.head",
    [],
    "Generated string namespace",
    ".str.head(n)",
    "Take the first `n` characters of the string values.",
    1,
    1,
  ],
  [
    "str.hex_decode",
    ".str.hex_decode",
    [],
    "Generated string namespace",
    ".str.hex_decode(strict)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "str.hex_encode",
    ".str.hex_encode",
    [],
    "Generated string namespace",
    ".str.hex_encode()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "str.json_path_match",
    ".str.json_path_match",
    [],
    "Generated string namespace",
    ".str.json_path_match(pat)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "str.len_bytes",
    ".str.len_bytes",
    [],
    "Generated string namespace",
    ".str.len_bytes()",
    "Return the length of each string as the number of bytes.  When working with non-ASCII text, the length in bytes is not the same as the length in characters. You may want to use [`len_chars`] instead. Note that `len_bytes",
    0,
    0,
  ],
  [
    "str.len_chars",
    ".str.len_chars",
    [],
    "Generated string namespace",
    ".str.len_chars()",
    "Return the length of each string as the number of characters.  When working with ASCII text, use [`len_bytes`] instead to achieve equivalent output with much better performance: [`len_bytes`] runs in _O(1)_, while `len_c",
    0,
    0,
  ],
  [
    "str.replace",
    ".str.replace",
    [],
    "Generated string namespace",
    ".str.replace(pat, value, literal)",
    "Replace values that match a regex `pat` with a `value`.",
    3,
    3,
  ],
  [
    "str.replace_all",
    ".str.replace_all",
    [],
    "Generated string namespace",
    ".str.replace_all(pat, value, literal)",
    "Replace all values that match a regex `pat` with a `value`.",
    3,
    3,
  ],
  [
    "str.replace_many",
    ".str.replace_many",
    [],
    "Generated string namespace",
    ".str.replace_many(patterns, replace_with, ascii_case_insensitive, leftmost)",
    "Uses aho-corasick to replace many patterns. # Arguments - `patterns`: an expression that evaluates to a String column - `replace_with`: an expression that evaluates to a String column - `ascii_case_insensitive`: Enable A",
    4,
    4,
  ],
  [
    "str.replace_n",
    ".str.replace_n",
    [],
    "Generated string namespace",
    ".str.replace_n(pat, value, literal, n)",
    "Replace values that match a regex `pat` with a `value`.",
    4,
    4,
  ],
  [
    "str.reverse",
    ".str.reverse",
    [],
    "Generated string namespace",
    ".str.reverse()",
    "Reverse each string",
    0,
    0,
  ],
  [
    "str.slice",
    ".str.slice",
    [],
    "Generated string namespace",
    ".str.slice(offset, length)",
    "Slice the string values.",
    2,
    2,
  ],
  [
    "str.split",
    ".str.split",
    [],
    "Generated string namespace",
    ".str.split(by)",
    "Split the string by a substring. The resulting dtype is `List<String>`.",
    1,
    1,
  ],
  [
    "str.split_exact",
    ".str.split_exact",
    [],
    "Generated string namespace",
    ".str.split_exact(by, n)",
    "Split exactly `n` times by a given substring. The resulting dtype is [`DataType::Struct`].",
    2,
    2,
  ],
  [
    "str.split_exact_inclusive",
    ".str.split_exact_inclusive",
    [],
    "Generated string namespace",
    ".str.split_exact_inclusive(by, n)",
    "Split exactly `n` times by a given substring and keep the substring. The resulting dtype is [`DataType::Struct`].",
    2,
    2,
  ],
  [
    "str.split_inclusive",
    ".str.split_inclusive",
    [],
    "Generated string namespace",
    ".str.split_inclusive(by)",
    "Split the string by a substring and keep the substring. The resulting dtype is `List<String>`.",
    1,
    1,
  ],
  [
    "str.split_regex",
    ".str.split_regex",
    [],
    "Generated string namespace",
    ".str.split_regex(pat, strict)",
    "Split the string by a regex pattern. The resulting dtype is `List<String>`.",
    2,
    2,
  ],
  [
    "str.split_regex_inclusive",
    ".str.split_regex_inclusive",
    [],
    "Generated string namespace",
    ".str.split_regex_inclusive(pat, strict)",
    "Split the string by a regex pattern and keep the matched substrings. The resulting dtype is `List<String>`.",
    2,
    2,
  ],
  [
    "str.splitn",
    ".str.splitn",
    [],
    "Generated string namespace",
    ".str.splitn(by, n)",
    "Split by a given substring, returning exactly `n` items. If there are more possible splits, keeps the remainder of the string intact. The resulting dtype is [`DataType::Struct`].",
    2,
    2,
  ],
  [
    "str.starts_with",
    ".str.starts_with",
    [],
    "Generated string namespace",
    ".str.starts_with(sub)",
    "Check if a string value starts with the `sub` string.",
    1,
    1,
  ],
  [
    "str.strip_chars",
    ".str.strip_chars",
    [],
    "Generated string namespace",
    ".str.strip_chars(matches)",
    "Remove leading and trailing characters, or whitespace if matches is None.",
    1,
    1,
  ],
  [
    "str.strip_chars_end",
    ".str.strip_chars_end",
    [],
    "Generated string namespace",
    ".str.strip_chars_end(matches)",
    "Remove trailing characters, or whitespace if matches is None.",
    1,
    1,
  ],
  [
    "str.strip_chars_start",
    ".str.strip_chars_start",
    [],
    "Generated string namespace",
    ".str.strip_chars_start(matches)",
    "Remove leading characters, or whitespace if matches is None.",
    1,
    1,
  ],
  [
    "str.strip_prefix",
    ".str.strip_prefix",
    [],
    "Generated string namespace",
    ".str.strip_prefix(prefix)",
    "Remove prefix.",
    1,
    1,
  ],
  [
    "str.strip_suffix",
    ".str.strip_suffix",
    [],
    "Generated string namespace",
    ".str.strip_suffix(suffix)",
    "Remove suffix.",
    1,
    1,
  ],
  [
    "str.tail",
    ".str.tail",
    [],
    "Generated string namespace",
    ".str.tail(n)",
    "Take the last `n` characters of the string values.",
    1,
    1,
  ],
  [
    "str.to_decimal",
    ".str.to_decimal",
    [],
    "Generated string namespace",
    ".str.to_decimal(scale)",
    "Convert a String column into a Decimal column.",
    1,
    1,
  ],
  [
    "str.zfill",
    ".str.zfill",
    [],
    "Generated string namespace",
    ".str.zfill(length)",
    "Pad the start of the string with zeros until it reaches the given length.  A sign prefix (`-`) is handled by inserting the padding after the sign character rather than before. Strings with length equal to or greater than",
    1,
    1,
  ],
  [
    "struct.field_by_index",
    ".struct.field_by_index",
    [],
    "Generated struct namespace",
    ".struct.field_by_index(index)",
    "See Polars documentation.",
    1,
    1,
  ],
  [
    "struct.json_encode",
    ".struct.json_encode",
    [],
    "Generated struct namespace",
    ".struct.json_encode()",
    "See Polars documentation.",
    0,
    0,
  ],
  [
    "struct.with_fields",
    ".struct.with_fields",
    [],
    "Generated struct namespace",
    ".struct.with_fields(fields)",
    "See Polars documentation.",
    1,
    1,
  ],
];

export const generatedFormulaFunctions: FormulaFunction[] = generatedDefinitions.map(
  (definition) => {
    const [
      id,
      name,
      aliases,
      category,
      signature,
      description,
      minimumArguments,
      maximumArguments,
    ] = definition;
    return {
      id,
      name,
      aliases,
      category,
      signature,
      description,
      minimumArguments,
      maximumArguments,
      returnType: generatedReturnType(id),
      nullBehavior: "native Polars behavior",
      // Browser preview has no Rust document behind it. Its fallback help is
      // the visible signature; desktop entries carry canonical argument prose.
      arguments: [],
    };
  }
);

function generatedReturnType(id: string): string {
  if (id.startsWith("str.") || id === "expr.to_titlecase") return "string";
  if (id.startsWith("dt.")) return "date";
  if (
    id.includes("is_null") ||
    id.includes("is_not_null") ||
    id.includes("is_nan") ||
    id.includes("is_finite") ||
    id.includes("is_infinite") ||
    id.includes("is_unique") ||
    id.includes("is_duplicated") ||
    id.includes("is_sorted") ||
    id.includes("starts_with") ||
    id.includes("ends_with") ||
    id.includes("contains")
  ) {
    return "boolean";
  }
  return "dynamic";
}
