// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a sweep of the data directory reclaimed.
 */
export type ArtifactSweep = { files: number; bytes: number };
