// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

/**
 * One line of a block: what was typed, and the parse of it if it parsed.
 *
 * Every line gets a name at birth (`line_1`, `line_2`, …) so it is always
 * addressable; naming is just renaming, and renaming is free because
 * references travel by the line's id. The id is document-unique, which is
 * what lets a formula anywhere hold one the way it holds a result's.
 *
 * The text is kept, and the parse is optional, which is the one place this
 * document model departs from parse-at-write. Everywhere else a formula
 * that does not parse is a refused edit, because everywhere else a formula
 * is committed deliberately. A scratchpad is half-typed by definition: it
 * is a draft surface, and refusing the keystroke that leaves `1 +` on the
 * screen would make it unusable. So a line that does not parse is stored
 * as it stands and reports its complaint in its own gutter.
 */
export type BlockLine = {
  id: string;
  /**
   * Empty on a blank or a comment line: those name nothing, and nothing
   * names them.
   */
  name: string;
  /**
   * Whether the name was typed (`x = 10`) or handed to the line so that
   * it could be referred to at all. Only a typed name is written back
   * into the block's text — an automatic one would put words in the
   * author's mouth.
   */
  named: boolean;
  /**
   * Whether a typed name was written in formula-style backticks. The
   * semantic name is stored without quoting; this bit only preserves the
   * author's spelling when the editable block text is reconstructed.
   */
  nameQuoted: boolean;
  /**
   * The line as typed, with any `name =` taken off the front.
   */
  source: string;
  /**
   * The parse of `source`, when there is one.
   */
  formula: Formula | null;
  /**
   * Why there is not one, when there is not: the parser's complaint, or
   * the reason a formula that parsed cannot be allowed to run — reading a
   * line below itself, or closing a loop. Kept rather than worked out
   * again at display time so the gutter shows the reason the edit found,
   * not a second opinion about it.
   */
  error: string | null;
};
