// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockLine } from "./BlockLine";

/**
 * An ordered list of expression lines — the scratchpad.
 *
 * The density mechanism for results: forty scratch calculations live on
 * one card instead of forty. A block is a namespace, not a new value kind
 * — each line is a result as specified above, and the block contributes
 * containment, ordering, and a qualified name. Lines within a block may
 * name each other bare; everything else reaches a line through the block,
 * `` `General calculations`.`account_balance` ``.
 *
 * Order is meaning: a line may read only the lines above it, so the block
 * reads top to bottom as a worked calculation. Across blocks the ordinary
 * dependency graph and cycle check apply, the same as between results.
 */
export type BlockObject = { id: string; name: string; lines: Array<BlockLine> };
