// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded window into one scratchwork answer. Scalar answers have one
 * value; list answers page without forcing the document snapshot or webview
 * to carry the whole series merely because the block is visible.
 */
export type BlockLinePage = {
  blockId: string;
  lineId: string;
  totalValues: number;
  offset: number;
  values: Array<string>;
};
