// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a broadcast list does to each column it meets.
 *
 * Arithmetic only, and deliberately not the complete formula operator set:
 * the gesture is "scale these" or "shift these", while comparisons already
 * belong to filters and ordinary calculated-column formulas.
 */
export type BroadcastOperator = "multiply" | "divide" | "add" | "subtract";
