// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a broadcast list does to each column it meets.
 *
 * Arithmetic only, and deliberately not [`crate::formula::ast::BinaryOperator`]:
 * the gesture is "scale these" or "shift these", and a broadcast that
 * answered True or False would be a filter wearing the wrong clothes.
 * Anything past these four is a formula, and a formula has a column
 * editor already.
 */
export type BroadcastOperator = "multiply" | "divide" | "add" | "subtract";
