// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { Row } from "./Row";

export type CalculationMatrixOutput = {
  columns: Array<Column>;
  rows: Array<Row>;
};
