// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationMatrixAxisFormula } from "./CalculationMatrixAxisFormula";
import type { CalculationMatrixBody } from "./CalculationMatrixBody";

/**
 * A compact two-axis authoring surface.  It is deliberately not a frame:
 * the axes and shared body are the authored facts; the long result is a
 * live projection rebuilt from them.
 */
export type CalculationMatrixObject = {
  id: string;
  name: string;
  rows: Array<CalculationMatrixAxisFormula>;
  columns: Array<CalculationMatrixAxisFormula>;
  body: CalculationMatrixBody;
};
