// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { Formula } from "./Formula";

export type CalculationMatrixAxisFormula = {
  id: string;
  /**
   * Explicit model input varied by this axis. Names remain local aliases;
   * matching a name must never silently change a model's dependencies.
   */
  targetId?: string;
  name: string;
  source: string;
  formula: Formula | null;
  dataType: DataType;
  error?: string;
};
