// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { Formula } from "./Formula";

export type CalculationMatrixAxisFormula = {
  id: string;
  name: string;
  source: string;
  formula: Formula | null;
  dataType: DataType;
  error?: string;
};
