// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalculationMatrixFormulaInput = {
  id?: string | null;
  targetId?: string;
  name: string;
  formula: string;
};
