// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeekPattern } from "./WeekPattern";
import type { YearEndRule } from "./YearEndRule";
import type { YearLabel } from "./YearLabel";

export type Calendar = {
  id: string;
  name: string;
  /**
   * Month the fiscal year starts on, 1 for January through 12.
   */
  fyStart: number;
  pattern: WeekPattern;
  /**
   * Meaningless for calendar months, which end on month ends.
   */
  yearEnd: YearEndRule;
  yearLabel: YearLabel;
  /**
   * ISO weekday numbers worked, Monday 1 through Sunday 7.
   */
  weekend: Array<number>;
  /**
   * Holidays as strict `YYYY-MM-DD` dates.
   */
  holidays: Array<string>;
};
