// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CanvasView = {
  id: string;
  /**
   * The object this card shows. On a card with tabs this is the selected
   * tab's object — switching tabs moves it.
   */
  objectId: string;
  x: number;
  y: number;
  width: number;
  height: number;
  collapsed: boolean;
  /**
   * The objects this card offers as tabs, in strip order.
   *
   * Empty means the card shows `object_id` alone and draws no strip.
   * Non-empty must contain `object_id`; that membership is what makes
   * "which tab is active" the same question as "what does this card
   * show", rather than a second piece of state that can disagree.
   *
   * Frames and plots both qualify: a plot of a frame on the card reads
   * the same data through the same lineage, so it belongs on the same
   * card. What may *not* appear is anything reading from somewhere the
   * card does not show — see `Document::validate_tab_target`.
   */
  tabObjectIds?: Array<string>;
};
