// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

export type Cell = {
  raw: string;
  /**
   * Absent rather than null when there is none, which is almost every cell.
   * Written out, `"overrideFormula":null` was about a quarter of the bytes
   * of a document holding literal rows -- on a 2 MB CSV opened as an
   * editable copy, some 7 MB of the 19 it serialized to.
   */
  overrideFormula?: Formula | null;
};
