// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

export type Cell = { raw: string; overrideFormula: Formula | null };
