// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayEntry } from "./OverlayEntry";

/**
 * One column's worth of typed-over values, sparse in the rows it names.
 */
export type CellOverlay = { columnId: string; entries: Array<OverlayEntry> };
