// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CliConnectionKind } from "./CliConnectionKind";
import type { CliOutputFormat } from "./CliOutputFormat";

export type CliConnectorProfile = {
  id: string;
  kind: CliConnectionKind;
  name: string;
  program: string;
  /**
   * One process argument per entry. `{source}` and `{query}` are replaced
   * inside the argument without ever passing through a shell.
   */
  arguments: Array<string>;
  output: CliOutputFormat;
};
