// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatisticType } from "./StatisticType";

export type Coefficient = {
  term: string;
  estimate: number | null;
  standardError: number | null;
  statistic: number | null;
  statisticType: StatisticType;
  pValue: number | null;
  confidenceLower: number | null;
  confidenceUpper: number | null;
};
