// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnFormatScale } from "./ColumnFormatScale";
import type { ColumnFormatStyle } from "./ColumnFormatStyle";

export type ColumnFormat = {
  style: ColumnFormatStyle;
  decimals?: number | null;
  scale?: ColumnFormatScale;
  negativeParens?: boolean | null;
  zeroDash?: boolean | null;
  currencyCode?: string | null;
};
