// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnFormat } from "./ColumnFormat";
import type { DataType } from "./DataType";
import type { Formula } from "./Formula";

export type Column = {
  id: string;
  name: string;
  /**
   * The physical field read from an imported artifact.
   *
   * This is deliberately separate from `name`: renaming a column in the
   * model must not make the parquet or SQL result retroactively rename its
   * field. `None` means the column is literal or produced by a formula.
   */
  sourceName?: string | null;
  dataType: DataType;
  categories?: Array<string>;
  format?: ColumnFormat | null;
  formula: Formula | null;
};
