// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { FrozenState } from "./FrozenState";
import type { ScalarValue } from "./ScalarValue";

/**
 * One line's worth of [`ComputedResult`], carrying the line's identity so
 * the interface can match answers back to lines without counting.
 */
export type ComputedBlockLine = {
  id: string;
  name: string;
  /**
   * This line's own text, so a gutter can be drawn from the answers
   * alone.
   */
  text: string;
  /**
   * Prose rather than arithmetic: no name, no answer, nothing in the
   * gutter.
   */
  comment: boolean;
  blank: boolean;
  dataType: DataType;
  frozen?: FrozenState;
  /**
   * Backward-compatible numeric projection. Non-numeric and null values use `None`.
   */
  value: number | null;
  typedValue: ScalarValue;
  display: string;
  error: string | null;
  isOverride: boolean;
};
