// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputedTextSegment } from "./ComputedTextSegment";

/**
 * A text card as the canvas shows it: the source to edit, and each piece
 * in order — prose verbatim, and every `{{…}}` hole with its answer as it
 * stands right now. Recomputed with every view, like a result: the card
 * can never print yesterday's number inside today's sentence.
 */
export type ComputedText = {
  /**
   * The card's editable text, reconstructed from the segments: prose
   * byte for byte, each hole rendered back from its formula — which is
   * how a rename elsewhere shows up here without an edit.
   */
  source: string;
  segments: Array<ComputedTextSegment>;
};
