// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A value object as the canvas shows it under the scenario in force.
 */
export type ComputedValue = {
  /**
   * The literal every formula reading this value will parse: the active
   * scenario's override, or the value's own `raw`.
   */
  raw: string;
  /**
   * The scenario supplying `raw`, when it is not the value's own. Present
   * is the whole signal — a card appends the name and shows the override,
   * absent and it is reading the base.
   *
   * The id travels beside the name because the card is editable: typing
   * over a displayed override has to change *that scenario's* number, not
   * the base the field is no longer showing.
   */
  scenarioId?: string;
  scenarioName?: string;
};
