// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScalarValue } from "./ScalarValue";

export type ComputedCell = {
  /**
   * Backward-compatible numeric projection. Non-numeric and null values use `None`.
   */
  value: number | null;
  typedValue: ScalarValue;
  display: string;
  error: string | null;
  isOverride: boolean;
};
