// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { ScalarValue } from "./ScalarValue";

export type ComputedTextSegment = { "kind": "literal"; text: string } | {
  "kind": "value";
  formula: string;
  dataType: DataType;
  /**
   * Backward-compatible numeric projection. Non-numeric and null values use `None`.
   */
  value: number | null;
  typedValue: ScalarValue;
  display: string;
  error: string | null;
  isOverride: boolean;
} | { "kind": "broken"; source: string; error: string };
