// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationMatrixOutput } from "./CalculationMatrixOutput";
import type { CalculationMatrixTuple } from "./CalculationMatrixTuple";
import type { ComputedCell } from "./ComputedCell";

export type ComputedCalculationMatrix = {
  rowTuples: Array<CalculationMatrixTuple>;
  columnTuples: Array<CalculationMatrixTuple>;
  cells: Array<Array<ComputedCell>>;
  output?: CalculationMatrixOutput;
  error?: string;
};
