// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suggestion } from "./Suggestion";

export type CompletionResult = {
  /**
   * Character offset into the formula text where `insert_text` should replace
   * through `cursor_pos` — i.e. the start of whatever the user has typed so
   * far for this token (empty when nothing has been typed yet).
   */
  replaceStart: number;
  receiverDtype: string | null;
  namespace: string | null;
  suggestions: Array<Suggestion>;
  note: string | null;
  /**
   * Catalog entry for the innermost call containing the cursor, when the
   * partial source names one. The UI already owns the catalog's prose; it
   * only needs the typed cursor context and current argument from core.
   */
  activeFunctionId: string | null;
  activeArgument: number | null;
};
