// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalculationMatrixOutput } from "./CalculationMatrixOutput";
import type { CalculationMatrixTuple } from "./CalculationMatrixTuple";
import type { ComputedCell } from "./ComputedCell";

export type ComputedCalculationMatrix = {
  rowTuples: Array<CalculationMatrixTuple>;
  columnTuples: Array<CalculationMatrixTuple>;
  cells: Array<Array<ComputedCell>>;
  output?: CalculationMatrixOutput;
  /**
   * How many times the model was evaluated to fill the grid, and how
   * long that took — reported only by sensitivity mode, where each cell
   * is a private copy of the document. An ordinary vectorized matrix is
   * one expression and says nothing here. Shown on the card because a
   * grid over a large model is expensive by nature and the person
   * asking should see the bill, not guess at it.
   */
  evaluations?: number;
  elapsedMs?: number;
  error?: string;
};
