// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputedCell } from "./ComputedCell";
import type { ComputedMaterialization } from "./ComputedMaterialization";
import type { FrameEditing } from "./FrameEditing";
import type { FrameStyleMatch } from "./FrameStyleMatch";
import type { RenderedFrameDerivation } from "./RenderedFrameDerivation";
import type { RenderedFrameStep } from "./RenderedFrameStep";

export type ComputedFrame = {
  /**
   * Everything that decides the rows this frame would hand back, as one
   * hash: its own definition and, recursively, every frame upstream.
   *
   * What a reader keys a cached page on. The document's revision number
   * would do the same job and do it far too eagerly — it moves for every
   * edit anywhere, so typing in a scratchpad on the other side of the
   * canvas would throw away every page of a million-row frame and fetch
   * them again. Lineage-scoped is the whole point of the hash.
   */
  fingerprint: string;
  formulas: { [key in string]: string };
  overrideFormulas: { [key in string]: { [key in string]: string } };
  rows: { [key in string]: { [key in string]: ComputedCell } };
  summaries: { [key in string]: ComputedCell };
  derivation: RenderedFrameDerivation | null;
  /**
   * The frame's transformation chain, every formula rendered back to the
   * text that was written rather than an expression tree.
   *
   * One field for both kinds of frame: a derived frame's chain and a
   * source frame's own chain are the same list of steps, and the editor
   * that shows them does not need to care which it is looking at.
   */
  steps?: Array<RenderedFrameStep>;
  /**
   * How many leading entries of `steps` are plumbing rather than
   * transformation: the identity projection a linked frame carries so it
   * owns its own column ids, and the select that adopts them.
   *
   * Nobody writes these, so the editor does not draw them — but it must
   * keep them. Dropping the projection would strand every column id this
   * frame has published to formulas, plots, and frames derived from it.
   */
  passThroughSteps?: number;
  /**
   * The display layer's filter and sort, rendered the same way — what the
   * View tab edits, against what the Wrangle tab edits above.
   */
  displaySteps?: Array<RenderedFrameStep>;
  /**
   * Row count when it is known without running a query: an artifact
   * records its own, and an in-memory frame is its rows. `None` means
   * the count would cost a full pass over the lazy plan -- a derived
   * frame read through pages -- so the caller takes it from the
   * [`FramePage`] it was going to read anyway. Counting eagerly here
   * would run a whole aggregation on every `view()`.
   */
  totalRows?: number;
  paged?: boolean;
  /**
   * Present when this frame is cached to a snapshot rather than read
   * live. `stale` means something upstream has changed since the
   * snapshot was written — the rows on screen are still the snapshot's,
   * and stay that way until it is refreshed.
   */
  materialization?: ComputedMaterialization;
  /**
   * A generated frame's rule, rendered back to the text a person would
   * retype — the editable face of `FrameObject::generator`, whose stored
   * expression tree the interface deliberately cannot read.
   */
  generatorRule?: string;
  /**
   * What this frame lets someone edit by hand, and why not when not.
   */
  editing: FrameEditing;
  /**
   * True when this frame's values can change without anyone editing the
   * document, because it — or something it reads from — re-reads a file.
   */
  live?: boolean;
  /**
   * The file this frame reads from, named for showing: "ledger.csv".
   *
   * The document holds the full path, which is the wrong length for a
   * list and the right length for a tooltip.
   */
  sourceName?: string;
  /**
   * True when a frame somewhere up this one's lineage is serving a stale
   * snapshot.
   *
   * Staleness inherits, because reading from old numbers produces old
   * numbers. A live frame computes honestly from whatever it is given,
   * and if what it is given is a snapshot nobody has refreshed, its own
   * rows are as out of date as that snapshot — with nothing in its own
   * definition to say so. A cached frame can carry both flags at once:
   * its snapshot can match its own lineage exactly and still have been
   * computed from a parent's stale one.
   */
  upstreamStale?: boolean;
  /**
   * What the conditional-formatting rules make of each row, by row id, in
   * the frame's own rule order.
   *
   * Only the rows this frame holds itself. A paged frame's rows arrive a
   * page at a time and carry their own matches on the page, because the
   * rules are run over the rows being read rather than over the frame.
   */
  styleMatches?: { [key in string]: Array<FrameStyleMatch> };
  /**
   * Rules that could not be run, by rule id, so the inspector can say so
   * against the rule that broke rather than failing the frame.
   */
  styleRuleErrors?: { [key in string]: string };
  /**
   * Each rule's hidden column rendered back to the text somebody wrote,
   * by rule id — the same service `formulas` performs for calculated
   * columns, and for the same reason: the interface reads formulas as
   * text and writes them back as text, and never opens an expression.
   */
  styleRuleFormulas?: { [key in string]: string };
};
