// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { FrozenState } from "./FrozenState";
import type { ScalarValue } from "./ScalarValue";
import type { SolveReport } from "./SolveReport";

/**
 * One line's worth of [`ComputedResult`], carrying the line's identity so
 * the interface can match answers back to lines without counting.
 */
export type ComputedBlockLine = {
  id: string;
  name: string;
  /**
   * This line's own text, so a gutter can be drawn from the answers
   * alone.
   */
  text: string;
  /**
   * Prose rather than arithmetic: no name, no answer, nothing in the
   * gutter.
   */
  comment: boolean;
  blank: boolean;
  dataType: DataType;
  /**
   * How many values this answer currently holds. Scalars are one; a live
   * vector carries its full current length even when the gutter only shows
   * a truncated preview.
   */
  valueCount: number;
  frozen?: FrozenState;
  /**
   * Present when the whole line is one `solve(...)` call: how the
   * answer was reached and which value it is for, so the gutter can
   * say so and offer to apply it.
   */
  solve?: SolveReport;
  /**
   * Backward-compatible numeric projection. Non-numeric and null values use `None`.
   */
  value: number | null;
  typedValue: ScalarValue;
  display: string;
  error: string | null;
  isOverride: boolean;
};
