// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { FrozenState } from "./FrozenState";
import type { ScalarValue } from "./ScalarValue";

/**
 * A result as the canvas shows it: the formula rendered back to text, and
 * the answer as it stands right now. Recomputed with every view, which is
 * what "live" means here — the card can never show yesterday's number
 * against today's inputs.
 */
export type ComputedResult = {
  formula: string;
  dataType: DataType;
  /**
   * Present when this answer was written down rather than worked out.
   */
  frozen?: FrozenState;
  /**
   * Backward-compatible numeric projection. Non-numeric and null values use `None`.
   */
  value: number | null;
  typedValue: ScalarValue;
  display: string;
  error: string | null;
  isOverride: boolean;
};
