// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputedBlockLine } from "./ComputedBlockLine";

/**
 * A block as the canvas shows it: the text to edit, and one answer per
 * line of it, in the block's own order — because the order is part of what
 * a block says, and because the gutter has to line up with the text.
 */
export type ComputedBlock = {
  /**
   * Every line's text, newline-joined: the block as somebody typed it,
   * with the names they typed still on the front of the lines they named.
   */
  source: string;
  lines: Array<ComputedBlockLine>;
};
