// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectorRecipe = { "kind": "file"; sourcePath: string } | {
  "kind": "cli";
  profileId: string;
  sourceLabel: string;
  query?: string | null;
} | {
  "kind": "database";
  connectionId: string;
  sourceName: string;
  query: string;
};
