// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentView } from "./DocumentView";
import type { SchemaDiff } from "./SchemaDiff";

/**
 * A refresh's two answers: the document as it now stands, and what the
 * refresh did to the frame's schema.
 *
 * The diff is returned rather than recorded. It is true about one moment —
 * the moment the new data arrived — and a document reopened tomorrow would
 * be lying if it still said a column had just appeared.
 */
export type ConnectorRefreshOutcome = {
  view: DocumentView;
  schema: SchemaDiff;
};
