// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A heading and the things kept under it.
 *
 * The spreadsheet version is a merged cell saying "Important lists" with
 * the lists sitting beneath it: a grouping that is real to the person
 * reading it and invisible to everything else. This one is real to the
 * formulas too — `` `Finance`.`Interest rate` `` — so the arrangement
 * that makes a canvas legible is the same arrangement you can write down.
 *
 * Values, lists, and containers may go in one; frames and plots may not.
 * A frame already has a card, a lineage, and somewhere it belongs, and
 * putting it inside something else would give "where does this live" two
 * answers. Nesting is allowed, and is checked for loops.
 *
 * Membership is a list on the container rather than a parent on each
 * member, which is what makes the order the one you arranged and keeps
 * "what is in here" a single place to read.
 */
export type ContainerObject = {
  id: string;
  name: string;
  memberIds: Array<string>;
};
