// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a crosstab view spreads a long frame wide: which column's values
 * become column headers, and which column fills the cells. Everything
 * else visible groups the rows.
 */
export type CrosstabDisplay = { namesColumnId: string; valuesColumnId: string };
