// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataType =
  | "string"
  | "categorical"
  | "integer"
  | "number"
  | "currency"
  | "percentage"
  | "boolean"
  | "date";
