// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactFormat } from "./ArtifactFormat";

export type DataArtifact = {
  id: string;
  path: string;
  rowCount: number;
  format: ArtifactFormat;
  sourceName: string;
};
