// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockObject } from "./BlockObject";
import type { ContainerObject } from "./ContainerObject";
import type { FrameObject } from "./FrameObject";
import type { PlotObject } from "./PlotObject";
import type { ResultObject } from "./ResultObject";
import type { SeriesObject } from "./SeriesObject";
import type { TextObject } from "./TextObject";
import type { ValueObject } from "./ValueObject";

/**
 * Measured: 704 bytes, all of it `FrameObject`. The other variants are
 * `ValueObject` 80, `PlotObject` 144, `TextObject` smaller still, so every
 * element of `Document::objects` is sized for a frame whether or not it is
 * one.
 *
 * Not boxed, deliberately. A document holds tens of objects, so the waste is
 * a few tens of KB, and the allocation `Box<FrameObject>` would add sits on
 * the path every frame read takes. The memory that actually matters here is
 * `Store::undo`, which clones whole documents — fixing that is worth more
 * than this, and is tracked separately.
 *
 * If this is ever revisited, boxing *this* variant is the high-leverage
 * change: it also shrinks `ReplicatedOperation`, whose largest variant is
 * `AddObject { object: DataObject, view: CanvasView }` at 704 + 136 = 840.
 */
export type DataObject =
  | { "kind": "value" } & ValueObject
  | { "kind": "result" } & ResultObject
  | { "kind": "block" } & BlockObject
  | { "kind": "series" } & SeriesObject
  | { "kind": "container" } & ContainerObject
  | { "kind": "frame" } & FrameObject
  | { "kind": "text" } & TextObject
  | { "kind": "plot" } & PlotObject;
