// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A date column's display pattern. `Iso` is the format the raw cell text
 * already carries, so it normalises away to `None` rather than being
 * stored as an explicit choice — see `normalized_column_format`.
 */
export type DatePattern =
  | "iso"
  | "dayMonthYear"
  | "monthDayYear"
  | "monthYear"
  | "quarter";
