// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row and column identities map original CSV tokens back to cells after
 * sorting, filtering, and renaming. The hash guards an external write; it
 * does not grant the workbook an unattended right to change that file.
 */
export type DelimitedFileOrigin = {
  path: string;
  sha256: string;
  rowIds: Array<string>;
  columnIds: Array<string>;
};
