// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The delimited file a frame was read from and may be written back to.
 *
 * `column_ids` names this document's column for each physical field of the
 * file, in the file's own order, which is what lets a renamed header still
 * find the tokens under it. There is deliberately no row list: a row is
 * named by its ordinal in the base read, which is the same ordinal a patch
 * is keyed by and the same one the page carries out, so the source line is
 * `ordinal + 1` and nothing has to be stored to say so. Carrying a UUID per
 * row was what made an opened file cost the size of the file rather than
 * the size of the corrections.
 *
 * The hash guards an external write; it does not grant the workbook an
 * unattended right to change that file.
 */
export type DelimitedFileOrigin = {
  path: string;
  sha256: string;
  columnIds: Array<string>;
};
