// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyKind } from "./DependencyKind";

/**
 * One stop on a dependency walk.
 */
export type DependencyNode = {
  objectId: string;
  name: string;
  kind: DependencyKind;
  /**
   * The formula as written, for a result. `None` for anything else.
   */
  formula: string | null;
  /**
   * The current value, rendered the way the canvas shows it.
   */
  display: string | null;
  error: string | null;
  children: Array<DependencyNode>;
};
