// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { ConnectorRecipe } from "./ConnectorRecipe";
import type { FrameStep } from "./FrameStep";

export type DisconnectedRead = {
  source: string;
  connector: ConnectorRecipe | null;
  columns: Array<Column>;
  baseColumns: Array<Column>;
  steps: Array<FrameStep>;
};
