// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasView } from "./CanvasView";
import type { ComputedBlock } from "./ComputedBlock";
import type { ComputedCalculationMatrix } from "./ComputedCalculationMatrix";
import type { ComputedFrame } from "./ComputedFrame";
import type { ComputedModel } from "./ComputedModel";
import type { ComputedResult } from "./ComputedResult";
import type { ComputedText } from "./ComputedText";
import type { ComputedValue } from "./ComputedValue";
import type { DataObject } from "./DataObject";
import type { FormulaFunction } from "./FormulaFunction";
import type { FrozenValue } from "./FrozenValue";
import type { Scenario } from "./Scenario";

export type DocumentView = {
  computedFrames: { [key in string]: ComputedFrame };
  computedResults: { [key in string]: ComputedResult };
  computedBlocks: { [key in string]: ComputedBlock };
  computedTexts: { [key in string]: ComputedText };
  computedCalculationMatrices: { [key in string]: ComputedCalculationMatrix };
  /**
   * What each value object holds right now, once the active scenario has
   * had its say. Keyed by value id.
   *
   * A separate map rather than a rewritten `raw` on the object itself:
   * the card has to be able to show the effective number *and* say that
   * it is not the one stored, and an interface handed only the override
   * could not tell an assumption apart from an edit.
   */
  computedValues: { [key in string]: ComputedValue };
  computedModels: { [key in string]: ComputedModel };
  formulaFunctions: Array<FormulaFunction>;
  canUndo: boolean;
  canRedo: boolean;
  /**
   * True when the document was opened without evaluation, so the interface
   * can say so and offer to turn it back on. The computed maps above are
   * empty in that state, not merely not-yet-filled.
   */
  safeMode: boolean;
  id: string;
  name: string;
  /**
   * ts-rs renders a `u64` as `bigint`, which is not what crosses the wire:
   * serde_json writes this as a plain JSON number and the interface has
   * always read it as one. A revision counter incremented once per edit is
   * nowhere near the range where the distinction could matter.
   */
  revision: number;
  objects: Array<DataObject>;
  views: Array<CanvasView>;
  /**
   * Answers computed from live data once and written down, keyed by the
   * result or block line that computed them.
   *
   * Kept here rather than on the objects themselves because both kinds of
   * holder — a result on a card, a line inside a block — are addressed by
   * the same sort of id, and a block's lines are rebuilt wholesale every
   * time its text is retyped. A frozen answer that lived on the line
   * would have to be carried through that rebuild by hand; one that lives
   * beside the document survives it by having the same id it always had.
   */
  frozenValues?: { [key in string]: FrozenValue };
  /**
   * Named assumption bundles: Base, Upside, Downside.
   *
   * A list rather than a map because the order is the order somebody put
   * them in, and a switcher that reshuffles itself alphabetically when a
   * scenario is renamed is a switcher nobody trusts.
   */
  scenarios: Array<Scenario>;
  /**
   * Which of them the document is reading through, or `None` for the
   * base — the numbers as the value cards hold them.
   *
   * Part of the document rather than of the session on purpose: an
   * activation changes every answer in the workbook, so it is an edit,
   * with an undo and a place in the history like any other.
   */
  activeScenario?: string | null;
};
