// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasView } from "./CanvasView";
import type { DataObject } from "./DataObject";
import type { FrozenValue } from "./FrozenValue";

export type Document = {
  id: string;
  name: string;
  /**
   * ts-rs renders a `u64` as `bigint`, which is not what crosses the wire:
   * serde_json writes this as a plain JSON number and the interface has
   * always read it as one. A revision counter incremented once per edit is
   * nowhere near the range where the distinction could matter.
   */
  revision: number;
  objects: Array<DataObject>;
  views: Array<CanvasView>;
  /**
   * Answers computed from live data once and written down, keyed by the
   * result or block line that computed them.
   *
   * Kept here rather than on the objects themselves because both kinds of
   * holder — a result on a card, a line inside a block — are addressed by
   * the same sort of id, and a block's lines are rebuilt wholesale every
   * time its text is retyped. A frozen answer that lived on the line
   * would have to be carried through that rebuild by hand; one that lives
   * beside the document survives it by having the same id it always had.
   */
  frozenValues?: { [key in string]: FrozenValue };
};
