// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryValue } from "./EntryValue";

/**
 * One hand-entered column on a computed frame: which column it fills,
 * which columns identify a row, and the values entered so far.
 *
 * `key_column_ids` is written down here rather than borrowed from
 * `unique_keys` so an edit to the frame's keys later cannot silently
 * re-address every entry; the column keeps meaning what it meant.
 */
export type EntryColumn = {
  columnId: string;
  keyColumnIds: Array<string>;
  entries?: Array<EntryValue>;
};
