// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entered value: the key column raws that name its row, and the raw
 * text entered, both in the document's own writing.
 */
export type EntryValue = { key: Array<string>; raw: string };
