// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column brought in by an expansion. The source id says what the
 * generator frame contributes; the output id is this frame's stable name
 * for it and prevents collisions with its own columns.
 */
export type ExpandOutput = { outputColumnId: string; sourceColumnId: string };
