// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CovarianceMethod } from "./CovarianceMethod";
import type { ForestSettings } from "./ForestSettings";
import type { Method } from "./Method";
import type { Settings } from "./Settings";

export type FitRequest = {
  method: Method;
  featureNames: Array<string>;
  targetName: string;
  confidenceLevel: number;
  covariance: CovarianceMethod;
  maxIterations: number;
  forest: ForestSettings;
  xgboost: Settings;
};
