// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelPayload } from "./ModelPayload";
import type { ModelSummary } from "./ModelSummary";

export type FittedModel = {
  version: number;
  featureNames: Array<string>;
  targetName: string | null;
  payload: ModelPayload;
  summary: ModelSummary;
  /**
   * Learned from training targets; absent for imported models. Never learned
   * from the labels subsequently supplied to evaluate().
   */
  trainingBaseline: number | null;
  trainingClassProbabilities: Array<number> | null;
};
