// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForestNode } from "./ForestNode";
import type { ForestSettings } from "./ForestSettings";

export type ForestModel = {
  features: number;
  classes: number | null;
  trees: Array<Array<ForestNode>>;
  settings: ForestSettings;
};
