// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForestSettings = {
  trees: number;
  maxDepth: number;
  minSamplesLeaf: number;
  maxFeatures: number | null;
  seed: number;
};
