// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForestNode = { "kind": "leaf"; value: number } | {
  "kind": "split";
  feature: number;
  threshold: number;
  left: number;
  right: number;
};
