// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormulaArgument = {
  /**
   * The stable argument name used by both positional and keyword calls.
   * Keeping it separate from the signature lets the UI mark the argument
   * under the cursor without trying to parse a Polars signature itself.
   */
  name: string;
  /**
   * Optional arguments are still shown in the signature, but nobody needs
   * to supply them to make the call valid.
   */
  required: boolean;
  /**
   * Concise, input-oriented guidance. This comes from the same catalog as
   * completion, so an argument cannot quietly acquire a second UI-only
   * meaning.
   */
  description: string;
  /**
   * A short expression in the formula language, where one is useful.
   */
  example: string | null;
};
