// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormulaArgument } from "./FormulaArgument";

export type FormulaFunction = {
  id: string;
  name: string;
  aliases: Array<string>;
  category: string;
  signature: string;
  description: string;
  minimumArguments: number;
  maximumArguments: number;
  returnType: string;
  nullBehavior: string;
  /**
   * Argument-level guidance for contextual formula help. The catalog owns
   * this rather than the frontend so catalog consumers and completion
   * teach the exact call shape the compiler accepts.
   */
  arguments: Array<FormulaArgument>;
};
