// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Formula = {
  /**
   * Opaque on the TypeScript side, deliberately, and this is the one place
   * that decision is written down.
   *
   * [`Expr`] is a wide recursive enum that exists to be evaluated, and the
   * interface never evaluates one: it reads formulas as *text*, rendered
   * back by the core (`ComputedFrame::formulas`, `RenderedFrameStep`), and
   * writes them back as text for the core to parse. Nothing in `src/` has
   * ever looked inside an expression tree, so generating a faithful mirror
   * of it would publish several hundred lines of union that no caller can
   * use — and would break the frontend build every time a variant is added
   * to a parser the frontend does not care about.
   *
   * `unknown` is therefore the honest type, not a shortcut: it says the
   * value round-trips through the frontend untouched, and it is what the
   * hand-written mirror said before this file generated it.
   */
  expression: unknown;
};
