// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameCellStyle } from "./FrameCellStyle";

/**
 * One rule's answer for one row, already read as style.
 *
 * The style rather than the value, because what a value means is the rule's
 * business: `true`, `"Refunded"`, and `-1284.20` are three different
 * questions with one answer shape. The rule id rides along so the interface
 * can tell which columns the answer is allowed to reach — the rule's own
 * scope — without knowing anything else about it.
 */
export type FrameStyleMatch = { ruleId: string; style: FrameCellStyle };
