// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this frame lets someone do to it by hand, and why not when not.
 *
 * Reported rather than left for the interface to work out. The rule is
 * small — does the frame own its rows — but it was being re-derived from
 * the model in every place that had to ask, so a grid, a context menu and
 * a paste path each carried their own copy of it and could each be wrong
 * on their own. One answer, computed where the rule is enforced.
 *
 * `reason` is written to be shown. A control that is simply missing, or
 * disabled without explanation, reads as a broken feature rather than a
 * frame that works differently — and "why can't I type here" has a real
 * answer worth giving.
 */
export type FrameEditing = {
  /**
   * Whether a value can be typed into a cell. Still false per-column for
   * a calculated column, which has a formula instead of a value.
   */
  cells: boolean;
  /**
   * Whether rows can be added or deleted by hand.
   */
  rows: boolean;
  /**
   * Whether a one-off override on a single cell takes effect.
   *
   * The narrower door in the wall, and it is not always open. An override
   * is recorded against a row of the document, and a frame read a page at
   * a time has no rows in the document to record it against — its values
   * are scanned from a parquet on every read, and the override would sit
   * there being nothing. Offering it anyway is how "the edit did nothing"
   * happens twice in one product.
   */
  overrides: boolean;
  reason?: string;
};
