// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameJoinType } from "./FrameJoinType";
import type { JoinOutput } from "./JoinOutput";

export type FrameJoin = {
  lookupFrameId: string;
  primaryKeyColumnIds: Array<string>;
  lookupKeyColumnIds: Array<string>;
  joinType: FrameJoinType;
  outputs: Array<JoinOutput>;
};
