// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputedCell } from "./ComputedCell";
import type { SummaryOperation } from "./SummaryOperation";

export type FrameSummaryRow = {
  operation: SummaryOperation;
  label: string;
  /**
   * Unsupported columns are deliberately absent. The interface renders
   * that absence as `n/a`, which distinguishes it from a supported
   * aggregate whose answer is null.
   */
  cells: { [key in string]: ComputedCell };
};
