// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape saved before text and fill could coexist on one scale.
 *
 * Kept public because old operations and documents are durable inputs. New
 * documents serialize [`FrameStyleScale::text`] and `fill`; deserialization
 * below promotes this property plus its colors into the corresponding ramp.
 */
export type FrameStyleScaleProperty = "fill" | "text";
