// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameStyleOutput } from "./FrameStyleOutput";

/**
 * A conditional-formatting rule as the inspector supplies it: the hidden
 * column still as text, and the reading of its answer already typed.
 * Existing ids preserve rule identity while editing; an omitted id is
 * minted during preparation so replicas receive the same ordered rule.
 */
export type FrameStyleRuleInput = {
  id?: string | null;
  formula: string;
  columnId?: string | null;
  output: FrameStyleOutput;
};
