// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";
import type { FrameStyleOutput } from "./FrameStyleOutput";

/**
 * A conditional-formatting rule: one hidden column, and how its answer is
 * read as style.
 *
 * The formula is an ordinary row-wise expression over the frame — the same
 * thing a calculated column holds — and what it *returns* decides how it is
 * read. A yes-or-no answer picks rows; a label sorts them into cases; a
 * number places them along a ramp. Nothing about the frame's data changes
 * either way: the column is computed, read as style, and dropped.
 */
export type FrameStyleRule = {
  id: string;
  formula: Formula;
  /**
   * `None` styles every cell in a matching row. A column id confines the
   * rule to that field while still allowing the formula to read any
   * field in the row.
   */
  columnId?: string | null;
  output: FrameStyleOutput;
};
