// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameCellStyle } from "./FrameCellStyle";

export type FrameStyleCase = {
  /**
   * The value as it is written in the data. Compared as text, because
   * that is what a category is.
   */
  value: string;
  style: FrameCellStyle;
};
