// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameStyleTarget =
  | { "kind": "frame" }
  | { "kind": "column"; columnId: string }
  | { "kind": "row"; rowId: string }
  | { "kind": "cell"; rowId: string; columnId: string };
