// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { FrameStyleMatch } from "./FrameStyleMatch";

export type FramePage = {
  frameId: string;
  totalRows: number;
  offset: number;
  limit: number;
  columns: Array<Column>;
  /**
   * The identity of each row on the page, in page order — what a cell
   * edit names. Positional for rows that came straight out of a scan and
   * so never had one.
   */
  rowIds: Array<string>;
  rows: Array<Array<string>>;
  /**
   * What the conditional-formatting rules make of each row on the page,
   * in page order and in the frame's own rule order.
   *
   * Read on the page rather than on the frame because a paged frame's
   * rows only exist as pages: the rules run over the thousand rows being
   * looked at, not over the four million behind them.
   */
  styleMatches?: Array<Array<FrameStyleMatch>>;
};
