// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which column says what time a row belongs to, and which columns restart
 * that timeline. A declaration, not a transformation: it names the Date
 * column whose values order the frame for period-relative reads (`prior`,
 * `period_index`), the way a unique key names the columns that identify a
 * row for lookups. The calendar — what counts as a period — stays an
 * argument on the functions themselves, so this never has to change when
 * a fiscal year does. Validated in `validate.rs` and read by the engine
 * when a formula asks for a neighbouring period rather than the row above.
 */
export type FramePeriod = {
  columnId: string;
  partitionColumnIds?: Array<string>;
};
