// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameStyleColorScale } from "./FrameStyleColorScale";

/**
 * A color ramp over a number that is already a position on it.
 *
 * The positions are fixed: low is 0, an optional middle is 0.5, high is 1,
 * and the formula says where each row sits between them. Text and fill each
 * choose independently whether they have that middle. That is the whole reason
 * the ramp carries no numbers of its own — a rule is a formula and a
 * reading of what it returns, and a scale that also held a domain was the
 * one reading that broke the rule by keeping data-dependent numbers beside
 * the formula instead of in it.
 *
 * `.normalize()` is what a formula usually says here, and everything a
 * domain used to express is an edit to it: pinned ends are
 * `.normalize(0, 100)`, a diverging scale is `.normalize(center=0)`,
 * outliers are `.clip(...)` first, and a value substituted from another
 * column is a `when(...)` in front. None of those needed a control.
 */
export type FrameStyleScale = {
  /**
   * A text-colour ramp, when the rule paints text.
   */
  text?: FrameStyleColorScale | null;
  /**
   * A fill-colour ramp, when the rule paints the cell background.
   */
  fill?: FrameStyleColorScale | null;
};
