// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The colors one property takes at a scale's fixed stops.
 *
 * Text and fill keep separate ramps because the readable ink over a fill is
 * not the fill itself. A scale may carry either or both; making one enum say
 * which property owned a shared set of colors was what made choosing a fill
 * silently discard the text color somebody had already chosen.
 */
export type FrameStyleColorScale = {
  /**
   * The color at 0.
   */
  low: string;
  /**
   * The color at 1.
   */
  high: string;
  /**
   * A color at 0.5, for a ramp that turns rather than climbs.
   *
   * Optional because two colors is the common case and a third nobody
   * asked for is a color they did not choose appearing in their data. It
   * exists for the *diverging* ramp, where the interesting number is in
   * the middle and the two directions away from it mean opposite things
   * — which the formula places, with `.normalize(center=0)` or whatever
   * else puts that number at a half.
   */
  mid?: string | null;
};
