// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameJoin } from "./FrameJoin";
import type { FrameStep } from "./FrameStep";

/**
 * What a derived frame reads, and what it does to it.
 *
 * A derivation is one of two things, and they are alternatives rather than
 * stages. A **join** is held flat, in `join`, with `steps` empty: it is a
 * single two-input operation whose output columns are minted when it is
 * written, and the join editor reads and writes that field directly.
 * Everything else is a **pipeline**: an ordered `steps` chain, with `join`
 * empty. Nothing creates both, and `steps()` hands back one list either
 * way, so almost nothing downstream has to ask which shape it is holding.
 */
export type FrameDerivation = {
  sourceFrameId: string;
  join: FrameJoin | null;
  steps?: Array<FrameStep>;
};
