// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExistingFormulaInput } from "./ExistingFormulaInput";
import type { PivotAggregate } from "./PivotAggregate";
import type { SortInput } from "./SortInput";

/**
 * A step as the editor supplies it: formulas still text, output columns
 * named rather than typed. Parsing and typing happen against the schema at
 * the step's own position, which is why the chain arrives whole rather than
 * a step at a time.
 */
export type FrameStepInput =
  | { "kind": "filter"; predicates: Array<string>; matchAll: boolean }
  | { "kind": "withColumns"; columns: Array<ExistingFormulaInput> }
  | { "kind": "select"; columnIds: Array<string> }
  | {
    "kind": "summarize";
    groupKeys: Array<ExistingFormulaInput>;
    aggregates: Array<ExistingFormulaInput>;
    maintainOrder: boolean;
  }
  | { "kind": "sort"; keys: Array<SortInput> }
  | { "kind": "union"; frameId: string }
  | { "kind": "expand"; frameId: string }
  | {
    "kind": "pivot";
    namesColumnId: string;
    valuesColumnId: string;
    aggregate: PivotAggregate;
  }
  | {
    "kind": "unpivot";
    columns: string;
    nameColumnId: string;
    nameColumnName: string;
    valueColumnId: string;
    valueColumnName: string;
  }
  | { "kind": "comment"; text: string };
