// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameCellStyle } from "./FrameCellStyle";
import type { FrameStyleCase } from "./FrameStyleCase";
import type { FrameStyleScale } from "./FrameStyleScale";

/**
 * How a rule's answer becomes style. The variant has to agree with what the
 * formula returns, which is checked when the rule is set.
 */
export type FrameStyleOutput =
  | { "kind": "condition"; style: FrameCellStyle }
  | {
    "kind": "category";
    cases: Array<FrameStyleCase>;
    other?: FrameCellStyle | null;
  }
  | { "kind": "scale"; scale: FrameStyleScale };
