// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellOverlay } from "./CellOverlay";
import type { Column } from "./Column";
import type { ConnectorRecipe } from "./ConnectorRecipe";
import type { DataArtifact } from "./DataArtifact";
import type { DelimitedFileOrigin } from "./DelimitedFileOrigin";
import type { DisconnectedRead } from "./DisconnectedRead";
import type { EntryColumn } from "./EntryColumn";
import type { FrameDerivation } from "./FrameDerivation";
import type { FrameDisplay } from "./FrameDisplay";
import type { FrameGenerator } from "./FrameGenerator";
import type { FrameStep } from "./FrameStep";
import type { Materialization } from "./Materialization";
import type { ModelPrediction } from "./ModelPrediction";
import type { Row } from "./Row";
import type { Summary } from "./Summary";
import type { UniqueKeyConstraint } from "./UniqueKeyConstraint";

export type FrameObject = {
  id: string;
  name: string;
  columns: Array<Column>;
  rows: Array<Row>;
  /**
   * The wrangle chain: what this frame *is*. A frame derived from this
   * one reads these steps, because they are part of its lineage.
   */
  steps?: Array<FrameStep>;
  /**
   * The display layer: how this frame is *shown*. Trailing filter and
   * sort applied after the wrangle chain, on this frame's own reads
   * only — a frame derived from this one never sees them.
   *
   * That one difference is the entire distinction between the Wrangle
   * tab and the View tab, and it is enforced in exactly one place:
   * recursive calls in [`Document::materialize_frame_lazy`] always ask
   * for [`Layer::Data`].
   *
   * [`Layer::Data`]: crate::Layer::Data
   * [`Document::materialize_frame_lazy`]: crate::Document::materialize_frame_lazy
   */
  display?: FrameDisplay;
  baseColumns?: Array<Column>;
  /**
   * A remark pinned to the frame: what it is, for the next reader.
   * Markdown, shown behind an icon rather than spending card space.
   */
  comment?: string | null;
  sourceFile?: string | null;
  /**
   * A retained recipe waiting for a replacement input after write-back.
   */
  disconnectedRead?: DisconnectedRead | null;
  /**
   * The external file this editable copy can explicitly write back to.
   * It is provenance, never a live row source or an editing gate.
   */
  fileOrigin?: DelimitedFileOrigin | null;
  artifact?: DataArtifact | null;
  connector?: ConnectorRecipe | null;
  derivation: FrameDerivation | null;
  /**
   * An ordinary derived frame whose rows are scored with a saved model.
   * Its derivation names the scoring input; learned state lives on the model.
   */
  prediction?: ModelPrediction | null;
  /**
   * Rows spelled as a rule instead of written down or read from a file:
   * `sequence(0, 16)`, or a date range whose bounds name a value on the
   * canvas. The document evaluates the rule on every read, so editing the
   * value regrows the frame — the whole point of writing rows this way.
   *
   * This is its own source kind, not a derivation, because a generator
   * has no upstream frame: every lineage walk that follows
   * `derivation.source_frame_id` correctly treats a generated frame as a
   * root. The one column the rule fills is `columns[0]`; a wrangle chain
   * in `steps` may build more on top of it.
   */
  generator?: FrameGenerator | null;
  materialization?: Materialization | null;
  uniqueKeys: Array<UniqueKeyConstraint>;
  /**
   * Hand-entered values living on a computed frame, keyed by row identity
   * rather than row position.
   *
   * A derived frame's rows are outputs and cannot be typed into — but the
   * *inputs a person owns* about those rows (hours against a generated
   * timesheet line, a note against a scenario) need somewhere to live
   * that survives the frame being regrown. Position dies on every
   * refresh; the key columns' values do not. So each entry column stores
   * its values against the row's key, and every read joins them back on.
   * An entry whose key no longer matches any row simply waits, unjoined,
   * for the row to come back.
   */
  entryColumns?: Array<EntryColumn>;
  /**
   * Values typed over a base this document reads rather than holds.
   *
   * The alternative was rewriting that base: a cell edit on a parquet-backed
   * frame used to read the whole file in, splice one value, and write a new
   * one, so correcting three cells in a large table cost three full rewrites
   * and left two orphans behind. A patch costs what it says instead, and the
   * artifact stays the content-addressed file the import wrote, which is
   * what lets two people read the same one.
   *
   * Keyed by the row's ordinal in that base, which is addressable exactly
   * when [`Self::carries_base_row_index`] holds. Positional keys cannot
   * survive the base being replaced, so nothing may refresh over a frame
   * that carries these — an entry column is the keyed answer for that case.
   */
  cellOverlay?: Array<CellOverlay>;
  /**
   * Ordinals of base rows struck out, in ascending order.
   *
   * Deleting a row from a base this document reads cannot mean removing it
   * from the file — that is what writing out does, on purpose and once.
   * Until then it is a note saying this row is not part of the result.
   */
  deletedRows?: Array<number>;
  /**
   * How many rows have been added past the end of the base read.
   *
   * They need no storage of their own: ordinals continue past the base, so
   * an added row is simply one whose every value is a patch. That keeps one
   * ordinal space, one patch mechanism, and one answer to "which row is
   * this" for a file that may be read again.
   */
  appendedRows?: number;
  summaries: Array<Summary>;
};
