// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameCellStyle } from "./FrameCellStyle";
import type { FrameStyleTarget } from "./FrameStyleTarget";

export type FrameStyle = { target: FrameStyleTarget; style: FrameCellStyle };
