// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameCellAlignment } from "./FrameCellAlignment";
import type { FrameLineStyle } from "./FrameLineStyle";

export type FrameCellStyle = {
  bold: boolean | null;
  italic: boolean | null;
  underline: boolean | null;
  textColor: string | null;
  fillColor: string | null;
  alignment: FrameCellAlignment | null;
  lineStyle: FrameLineStyle | null;
};
