// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Polars plan behind a frame as it is displayed, as text.
 *
 * `logical` is the plan as written -- wrangle chain, then the display
 * filter and sort -- and `optimized` is what Polars actually runs after
 * predicate pushdown and projection pruning. Reading both is how you
 * confirm a filter written against one frame reached the scan of the frame
 * it was derived from.
 */
export type FrameQueryPlan = {
  frameId: string;
  logical: string;
  optimized: string;
};
