// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

/**
 * The rule a generated frame's rows come from.
 *
 * The expression is scalar-scoped — it may name values, results, and block
 * lines, never a column of any frame — and it must come back list-shaped or
 * as one value. `sequence(...)` is the expected spelling, but a written
 * list works the same way. Bounds that reference a value are what make a
 * generated calendar follow its anchor date around.
 */
export type FrameGenerator = { formula: Formula };
