// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrosstabDisplay } from "./CrosstabDisplay";
import type { FrameStep } from "./FrameStep";
import type { FrameStyle } from "./FrameStyle";
import type { FrameStyleRule } from "./FrameStyleRule";
import type { FrameViewOrientation } from "./FrameViewOrientation";
import type { SummaryOperation } from "./SummaryOperation";

/**
 * Everything about a frame that is presentation rather than lineage.
 *
 * `steps` is the same [`FrameStep`] the wrangle chain uses and runs through
 * the same evaluator, so a display filter and a wrangle filter are the same
 * code path with the same null ordering. Only [`FrameStep::Filter`] and
 * [`FrameStep::Sort`] may appear here, and only in that order — a display
 * layer that could add or drop columns would change the frame's schema
 * contract, which is a lineage change by definition.
 */
export type FrameDisplay = {
  steps?: Array<FrameStep>;
  /**
   * Whole-frame footer rows, in display order.
   *
   * These live with filters, sorting and orientation because they describe
   * how this frame is being looked at, not another transformation in its
   * lineage. The results are queried on demand: keeping a footer on a
   * million-row import must not rescan it whenever an unrelated canvas
   * object changes.
   * `None` is an older document whose per-column summaries should be
   * projected into footer rows. `Some([])` is a deliberate choice to show
   * no rows. Keeping those states distinct means Clear stays cleared
   * without making old workbooks lose their summaries on open.
   */
  summaryRows?: Array<SummaryOperation> | null;
  /**
   * Whether the profile drawer below the records grid is expanded.
   */
  summaryDrawerOpen?: boolean;
  /**
   * The drawer's own height, independent of its card's outer height.
   * Absence means the compact interface default rather than a second
   * hard-coded value written into every document.
   */
  summaryDrawerHeight?: number | null;
  orientation: FrameViewOrientation;
  /**
   * A long frame shown wide: one row per key, one column per value of
   * the names column, cells from the values column. Display only — the
   * data stays long, which is what makes this safe where a pivot step is
   * not: a *view* has no schema for other frames to depend on, so it may
   * follow the data freely. The editable crosstab over an entry column
   * is the spreadsheet-shaped face of a keyed long frame.
   */
  crosstab?: CrosstabDisplay | null;
  styles?: Array<FrameStyle>;
  /**
   * Ordered, row-wise presentation rules. Their predicates are formulas
   * over this frame, but their answers never become data columns: they
   * only contribute sparse style properties to the rendered view.
   */
  styleRules?: Array<FrameStyleRule>;
};
