// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { ConnectorRecipe } from "./ConnectorRecipe";
import type { DataArtifact } from "./DataArtifact";
import type { EntryColumn } from "./EntryColumn";
import type { FrameDerivation } from "./FrameDerivation";
import type { FrameDisplay } from "./FrameDisplay";
import type { FrameGenerator } from "./FrameGenerator";
import type { FrameStep } from "./FrameStep";
import type { Materialization } from "./Materialization";
import type { Row } from "./Row";
import type { Summary } from "./Summary";
import type { UniqueKeyConstraint } from "./UniqueKeyConstraint";

export type FrameObject = {
  id: string;
  name: string;
  columns: Array<Column>;
  rows: Array<Row>;
  /**
   * The wrangle chain: what this frame *is*. A frame derived from this
   * one reads these steps, because they are part of its lineage.
   */
  steps?: Array<FrameStep>;
  /**
   * The display layer: how this frame is *shown*. Trailing filter and
   * sort applied after the wrangle chain, on this frame's own reads
   * only — a frame derived from this one never sees them.
   *
   * That one difference is the entire distinction between the Wrangle
   * tab and the View tab, and it is enforced in exactly one place:
   * recursive calls in [`Document::materialize_frame_lazy`] always ask
   * for [`Layer::Data`].
   *
   * [`Layer::Data`]: crate::Layer::Data
   * [`Document::materialize_frame_lazy`]: crate::Document::materialize_frame_lazy
   */
  display?: FrameDisplay;
  baseColumns?: Array<Column>;
  /**
   * A remark pinned to the frame: what it is, for the next reader.
   * Markdown, shown behind an icon rather than spending card space.
   */
  comment?: string | null;
  sourceFile?: string | null;
  artifact?: DataArtifact | null;
  connector?: ConnectorRecipe | null;
  derivation: FrameDerivation | null;
  /**
   * Rows spelled as a rule instead of written down or read from a file:
   * `sequence(0, 16)`, or a date range whose bounds name a value on the
   * canvas. The document evaluates the rule on every read, so editing the
   * value regrows the frame — the whole point of writing rows this way.
   *
   * This is its own source kind, not a derivation, because a generator
   * has no upstream frame: every lineage walk that follows
   * `derivation.source_frame_id` correctly treats a generated frame as a
   * root. The one column the rule fills is `columns[0]`; a wrangle chain
   * in `steps` may build more on top of it.
   */
  generator?: FrameGenerator | null;
  materialization?: Materialization | null;
  uniqueKeys: Array<UniqueKeyConstraint>;
  /**
   * Hand-entered values living on a computed frame, keyed by row identity
   * rather than row position.
   *
   * A derived frame's rows are outputs and cannot be typed into — but the
   * *inputs a person owns* about those rows (hours against a generated
   * timesheet line, a note against a scenario) need somewhere to live
   * that survives the frame being regrown. Position dies on every
   * refresh; the key columns' values do not. So each entry column stores
   * its values against the row's key, and every read joins them back on.
   * An entry whose key no longer matches any row simply waits, unjoined,
   * for the row to come back.
   */
  entryColumns?: Array<EntryColumn>;
  summaries: Array<Summary>;
};
