// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataArtifact } from "./DataArtifact";

/**
 * An answer computed from live data once and written down.
 *
 * The third thing a formula can do about a frame that has no snapshot.
 * Materializing the frame records all 900,000 rows to get at one number,
 * which is the wrong trade when the number is all you wanted; refusing the
 * reference, which is what happened before this existed, makes the user
 * materialize anyway. Freezing records the answer instead — a few bytes of
 * parquet, refreshed on demand.
 *
 * It also keeps the document acyclic for free, and by the same argument
 * snapshots do: a written-down answer is inert. A formula that reads one
 * reads a recorded fact, not a computation that might lead back round to
 * itself, so nothing here has to watch its own feet.
 */
export type FrozenValue = {
  artifact: DataArtifact;
  /**
   * Everything that decided this answer — the formula, and the lineage of
   * every frame it reads — as it stood when the answer was taken. When
   * the two disagree the answer is stale, which is a thing to say on the
   * card rather than a thing to fix behind someone's back.
   */
  fingerprint: string;
  /**
   * When it was taken, to say so on the card. Recorded rather than
   * derived: a frozen answer's age is the whole reason to look at it.
   */
  takenAt: string;
};
