// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A frozen answer as the card reports it: when it was taken, and whether
 * anything it was taken from has changed since.
 */
export type FrozenState = { takenAt: string; stale: boolean };
