// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassLabel } from "./ClassLabel";
import type { Input } from "./Input";
import type { Recipe } from "./Recipe";

export type ImportedLinear = {
  inputs: Array<Input>;
  recipe: Recipe;
  coefficients: Array<number>;
  intercepts: Array<number>;
  labels: Array<ClassLabel>;
};
