// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnBinding } from "./ColumnBinding";
import type { Dtype } from "./Dtype";
import type { Role } from "./Role";

export type Input = {
  slot: string;
  name: string;
  dtype: Dtype;
  role: Role;
  binding: ColumnBinding | null;
};
