// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JoinDiagnostics = {
  primaryRows: number;
  matchedRows: number;
  unmatchedRows: number;
  lookupRows: number;
  /**
   * Lookup rows missing at least one piece of the proposed key.
   */
  lookupNullKeyRows: number;
  /**
   * Distinct non-null key values that occur more than once.
   */
  lookupDuplicateKeyValues: number;
};
