// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataArtifact } from "./DataArtifact";

export type Materialization = { artifact: DataArtifact; fingerprint: string };
