// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuGroup } from "./MenuGroup";

/**
 * One application command exactly as the menu declares it.
 */
export type MenuCommand = {
  /**
   * The payload the webview receives on [`MENU_COMMAND_EVENT`].
   */
  id: string;
  label: string;
  /**
   * The platform accelerator string Tauri binds, e.g. `CmdOrCtrl+Shift+P`.
   * `None` for an item deliberately left without a key equivalent.
   */
  accelerator: string | null;
  group: MenuGroup;
};
