// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which menu draws the command.
 *
 * Not decoration. Three hand-maintained lists used to name these same
 * actions — the menu, the command palette, and the set the Scratchwork
 * pop-out forwards to its workbook — and nothing compared them, so a new
 * item could be enabled in the pop-out and inert, or missing from ⇧⌘P,
 * with everything still compiling. The group travels with the id so the
 * frontend's checks can report a drift in the terms a person would use.
 */
export type MenuGroup = "file" | "edit" | "insert" | "view" | "window" | "help";
