// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metrics = {
  rows: number;
  rmse: number | null;
  mae: number | null;
  rSquared: number | null;
  accuracy: number | null;
  logLoss: number | null;
  baselineRmse: number | null;
  baselineAccuracy: number | null;
  baselineLogLoss: number | null;
};
