// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissingValue = { "kind": "nan" } | { "kind": "null" } | {
  "kind": "string";
  "value": string;
} | { "kind": "number"; "value": number };
