// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlError =
  | { "kind": "invalidInput"; "message": string }
  | { "kind": "unsupported"; "message": string }
  | { "kind": "resourceLimit"; "message": string }
  | { "kind": "rankDeficient" }
  | { "kind": "separation" }
  | { "kind": "inconclusiveSeparation" }
  | { "kind": "nonConvergence" }
  | { "kind": "numerical"; "message": string }
  | { "kind": "invalidModel"; "message": string };
