// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coefficient } from "./Coefficient";
import type { CovarianceMethod } from "./CovarianceMethod";
import type { Metrics } from "./Metrics";

export type ModelSummary = {
  coefficients: Array<Coefficient>;
  trainingMetrics: Metrics;
  observations: number | null;
  covariance: CovarianceMethod | null;
  confidenceLevel: number | null;
  residualDegreesOfFreedom: number | null;
  warnings: Array<string>;
};
