// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelPrediction = {
  modelId: string;
  featureColumnIds: Array<string>;
  /**
   * Stable output addresses survive retraining and source renaming.
   */
  outputColumnIds: Array<string>;
};
