// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelFit } from "./ModelFit";
import type { ModelInput } from "./ModelInput";
import type { ModelSpec } from "./ModelSpec";

export type ModelObject = {
  id: string;
  name: string;
  spec: ModelSpec | null;
  fitted: ModelFit | null;
  /**
   * A default scoring binding, not training provenance. Changing scoring
   * rows cannot make an imported fitted model stale.
   */
  importedInput: ModelInput | null;
};
