// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForestModel } from "./ForestModel";
import type { ImportedLinear } from "./ImportedLinear";
import type { XgboostModel } from "./XgboostModel";

export type ModelPayload =
  | { "kind": "linear"; intercept: number; coefficients: Array<number> }
  | { "kind": "binaryLogistic"; intercept: number; coefficients: Array<number> }
  | { "kind": "onnx"; model: ImportedLinear }
  | { "kind": "randomForest"; model: ForestModel }
  | { "kind": "xgboost"; model: XgboostModel };
