// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FittedModel } from "./FittedModel";
import type { Metrics } from "./Metrics";
import type { ModelSpec } from "./ModelSpec";
import type { ModelSplit } from "./ModelSplit";

export type ModelFit = {
  id: string;
  trainingRevision: number;
  trainingFingerprint: string | null;
  /**
   * The recipe that produced this fit, which may differ from the draft
   * specification after editing. Failed retraining never replaces this.
   */
  spec: ModelSpec | null;
  result: FittedModel;
  evaluationMetrics: Metrics | null;
  split: ModelSplit | null;
};
