// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CovarianceMethod } from "./CovarianceMethod";
import type { ForestSettings } from "./ForestSettings";
import type { Method } from "./Method";

export type ModelSpec = {
  sourceFrameId: string;
  targetColumnId: string | null;
  featureColumnIds: Array<string>;
  method: Method;
  covariance: CovarianceMethod;
  confidenceLevel: number;
  holdoutFraction: number;
  seed: number;
  forest?: ForestSettings;
};
