// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellUpdate } from "./CellUpdate";
import type { ColumnFormat } from "./ColumnFormat";
import type { ConnectorRecipe } from "./ConnectorRecipe";
import type { CrosstabDisplay } from "./CrosstabDisplay";
import type { DataArtifact } from "./DataArtifact";
import type { DataType } from "./DataType";
import type { DerivedSort } from "./DerivedSort";
import type { FrameCellStyle } from "./FrameCellStyle";
import type { FrameJoinType } from "./FrameJoinType";
import type { FrameStepInput } from "./FrameStepInput";
import type { FrameStyleRuleInput } from "./FrameStyleRuleInput";
import type { FrameStyleTarget } from "./FrameStyleTarget";
import type { FrameViewOrientation } from "./FrameViewOrientation";
import type { FrozenValue } from "./FrozenValue";
import type { JoinColumnInput } from "./JoinColumnInput";
import type { NamedFormulaInput } from "./NamedFormulaInput";
import type { SummaryOperation } from "./SummaryOperation";

export type Operation =
  | {
    "type": "addValue";
    name: string;
    raw: string;
    x: number;
    y: number;
    /**
     * The container to put it straight into. Adding something to a
     * heading is one act, not an add followed by a move.
     */
    containerId?: string | null;
  }
  | {
    "type": "addResult";
    name: string;
    formula: string;
    x: number;
    y: number;
    containerId?: string | null;
  }
  | { "type": "setResultFormula"; objectId: string; formula: string }
  | { "type": "addBlock"; name: string; x: number; y: number }
  | {
    "type": "setBlockSource";
    blockId: string;
    source: string;
    editing?: number | null;
  }
  | { "type": "addText"; x: number; y: number }
  | { "type": "setTextSource"; objectId: string; source: string }
  | {
    "type": "addContainer";
    name: string;
    x: number;
    y: number;
    containerId?: string | null;
  }
  | {
    "type": "moveIntoContainer";
    objectId: string;
    containerId?: string | null;
  }
  | {
    "type": "addSeries";
    name: string;
    values: string;
    x: number;
    y: number;
    containerId?: string | null;
  }
  | {
    "type": "importSeriesFromFile";
    containerId?: string | null;
    name: string;
    path: string;
    column?: string | null;
    x: number;
    y: number;
  }
  | { "type": "setSeries"; objectId: string; values: string }
  | { "type": "setSeriesType"; objectId: string; dataType: DataType }
  | {
    "type": "addFrame";
    name: string;
    grid: Array<Array<string>>;
    x: number;
    y: number;
  }
  | {
    "type": "addGeneratorFrame";
    name: string;
    /**
     * The rule as formula text, scalar-scoped like a scratchpad line.
     */
    formula: string;
    /**
     * What to call the generated column. Defaults to the frame's name.
     */
    columnName: string | null;
    x: number;
    y: number;
  }
  | { "type": "setFrameGenerator"; frameId: string; formula: string }
  | {
    "type": "addEntryColumn";
    frameId: string;
    name: string;
    dataType: DataType;
    keyColumnIds: Array<string>;
  }
  | {
    "type": "setEntryValue";
    frameId: string;
    columnId: string;
    key: Array<string>;
    raw: string;
  }
  | { "type": "refreshFramePipeline"; frameId: string }
  | {
    "type": "importFrameFromFile";
    name: string;
    path: string;
    x: number;
    y: number;
  }
  | {
    "type": "importFrameFromArtifact";
    name: string;
    artifact: DataArtifact;
    connector: ConnectorRecipe | null;
    x: number;
    y: number;
  }
  | { "type": "refreshFrameArtifact"; frameId: string; artifact: DataArtifact }
  | {
    "type": "setFrameSource";
    frameId: string;
    artifact: DataArtifact;
    connector: ConnectorRecipe;
  }
  | {
    "type": "addPlot";
    name: string;
    sourceFrameId: string;
    spec: Record<string, unknown>;
    x: number;
    y: number;
    /**
     * The card to add the plot to as a tab, when it should live beside
     * the frame it draws rather than in a window of its own. `x`/`y`
     * are ignored then — a tab has no position.
     */
    viewId?: string | null;
  }
  | { "type": "renameObject"; objectId: string; name: string }
  | { "type": "deleteObject"; objectId: string }
  | { "type": "setValue"; objectId: string; raw: string }
  | { "type": "setPlotSpec"; plotId: string; spec: Record<string, unknown> }
  | { "type": "moveView"; viewId: string; x: number; y: number }
  | { "type": "resizeView"; viewId: string; width: number; height: number }
  | { "type": "setViewCollapsed"; viewId: string; collapsed: boolean }
  | { "type": "tidyLayout" }
  | {
    "type": "setFrameDisplayOrientation";
    frameId: string;
    orientation: FrameViewOrientation;
  }
  | {
    "type": "setFrameDisplayCrosstab";
    frameId: string;
    crosstab: CrosstabDisplay | null;
  }
  | { "type": "branchFrame"; viewId: string; frameId: string }
  | {
    "type": "moveTab";
    sourceViewId: string;
    targetViewId: string;
    objectId: string;
    targetIndex: number;
  }
  | {
    "type": "detachTab";
    viewId: string;
    objectId: string;
    x: number;
    y: number;
  }
  | { "type": "setActiveTab"; viewId: string; objectId: string }
  | {
    "type": "setFrameDisplayFilter";
    frameId: string;
    filters: Array<string>;
    filterMatchAll: boolean;
  }
  | { "type": "setFrameDisplaySort"; frameId: string; keys: Array<DerivedSort> }
  | {
    "type": "setFrameSummaryRows";
    frameId: string;
    summaryRows: Array<SummaryOperation>;
  }
  | {
    "type": "setFrameSummaryDrawer";
    frameId: string;
    open: boolean;
    height?: number | null;
  }
  | {
    "type": "setFrameStyle";
    frameId: string;
    target: FrameStyleTarget;
    style: FrameCellStyle;
  }
  | {
    "type": "setFrameStyleRules";
    frameId: string;
    rules: Array<FrameStyleRuleInput>;
  }
  | {
    "type": "setCell";
    frameId: string;
    rowId: string;
    columnId: string;
    raw: string;
  }
  | { "type": "setCells"; frameId: string; cells: Array<CellUpdate> }
  | { "type": "addRow"; frameId: string; values: { [key in string]: string } }
  | { "type": "setFrameFromPastedText"; frameId: string; text: string }
  | {
    "type": "pasteCells";
    frameId: string;
    rowId: string;
    columnId: string;
    grid: Array<Array<string>>;
  }
  | { "type": "deleteRow"; frameId: string; rowId: string }
  | {
    "type": "addColumn";
    frameId: string;
    name: string;
    dataType: DataType;
    afterColumnId: string | null;
  }
  | { "type": "deleteColumn"; frameId: string; columnId: string }
  | { "type": "renameColumn"; frameId: string; columnId: string; name: string }
  | {
    "type": "setColumnType";
    frameId: string;
    columnId: string;
    dataType: DataType;
  }
  | {
    "type": "setColumnCategories";
    frameId: string;
    columnId: string;
    categories: Array<string>;
  }
  | {
    "type": "setColumnFormat";
    frameId: string;
    columnId: string;
    format: ColumnFormat | null;
  }
  | {
    "type": "addComputedColumn";
    frameId: string;
    name: string;
    formula: string;
    /**
     * `None` preserves the original append behavior for older clients.
     */
    afterColumnId?: string | null;
  }
  | {
    "type": "setColumnFormula";
    frameId: string;
    columnId: string;
    formula: string;
  }
  | {
    "type": "setCellOverride";
    frameId: string;
    rowId: string;
    columnId: string;
    formula: string | null;
  }
  | {
    "type": "addSummary";
    frameId: string;
    columnId: string;
    operation: SummaryOperation;
  }
  | {
    "type": "addDerivedFrame";
    sourceFrameId: string;
    name: string;
    groupKeys: Array<NamedFormulaInput>;
    aggregates: Array<NamedFormulaInput>;
    maintainOrder: boolean;
    x: number;
    y: number;
  }
  | {
    "type": "addLinkedFrame";
    sourceFrameId: string;
    name: string;
    x: number;
    y: number;
  }
  | { "type": "renameDocument"; name: string }
  | {
    "type": "setFrameMaterialization";
    frameId: string;
    artifact: DataArtifact;
  }
  | { "type": "clearFrameMaterialization"; frameId: string }
  | { "type": "setFrozenValue"; objectId: string; frozen: FrozenValue | null }
  | { "type": "packageDocument"; adopted: Array<[string, DataArtifact]> }
  | { "type": "adoptFrameRows"; frameId: string; artifact: DataArtifact }
  | { "type": "promoteDisplayToSteps"; frameId: string }
  | {
    "type": "setUniqueKey";
    frameId: string;
    columnIds: Array<string>;
    enabled: boolean;
  }
  | {
    "type": "addJoinFrame";
    primaryFrameId: string;
    lookupFrameId: string;
    primaryKeyColumnIds: Array<string>;
    lookupKeyColumnIds: Array<string>;
    joinType: FrameJoinType;
    columns: Array<JoinColumnInput>;
    name: string;
    x: number;
    y: number;
  }
  | {
    "type": "setFramePipeline";
    frameId: string;
    steps: Array<FrameStepInput>;
  }
  | { "type": "setFrameComment"; frameId: string; comment?: string | null };
