// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One typed-over value: the row it belongs to, by ordinal in the base read,
 * and the text entered, in the document's own writing.
 */
export type OverlayEntry = { rowOrdinal: number; raw: string };
