// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScalarValue } from "./ScalarValue";

export type ParameterControl =
  | {
    "type": "slider";
    start: number;
    stop: number;
    step: number;
    value: number;
  }
  | { "type": "dropdown"; options: Array<ScalarValue>; value: ScalarValue }
  | { "type": "dateInput"; value: string };
