// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { StepSchema } from "./StepSchema";

/**
 * What a chain looks like at every position: the columns each step leaves
 * behind, and where the walk stopped if a step could not be worked out.
 *
 * Answered from the query plan, which costs no scan — `collect_schema()`
 * resolves names and types without touching a row, and every step that
 * exists today is resolvable that way.
 *
 * The pivot step is the one that tested this, and it chose to keep it
 * true: its output columns are named after the *values* in a column, so
 * it looks at the data once, when the step is written, and bakes what it
 * finds into the step — the way a join bakes its outputs. After that the
 * schema is a property of the plan again. A step that instead chooses to
 * be genuinely data-dependent — unnesting fields not known ahead of time
 * — cannot be answered without running the query, which is why a step's
 * schema stays a struct rather than a bare column list: such a step will
 * need to say so, so the editor can offer to run a sample instead of
 * quietly showing the wrong shape.
 */
export type PipelineSchema = {
  frameId: string;
  /**
   * What the first step sees.
   */
  inputColumns: Array<Column>;
  /**
   * One entry per step the walk got through, in order.
   */
  steps: Array<StepSchema>;
  /**
   * The step that stopped the walk, if one did. Steps at and after this
   * index have no schema, because working one out needs the step before
   * it to have parsed.
   */
  failedStep: number | null;
  error: string | null;
};
