// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column a pivot produces: the value of the names column it stands
 * for, and the id the rest of the document knows it by. Keeping the id
 * here is what lets a re-saved pivot hand the same value the same column
 * identity, so formats and references on it survive the edit.
 */
export type PivotOutput = { outputColumnId: string; value: string };
