// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a pivot settles several rows landing in one cell. There is always
 * a policy, even over clean data: a pivot's cell is defined by two
 * coordinates that nothing guarantees are unique. `None` is the policy
 * of refusing — the cell holds the one row it gets, and a second row
 * landing there is an error rather than something quietly combined,
 * which is the behaviour to pick when the data is supposed to already
 * be one row per cell and being told otherwise is the point.
 */
export type PivotAggregate =
  | "sum"
  | "count"
  | "mean"
  | "min"
  | "max"
  | "first"
  | "none";
