// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlotObject = {
  id: string;
  name: string;
  sourceFrameId: string;
  spec: Record<string, unknown>;
};
