// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PredictionOutput = {
  /**
   * Numerical response for regression; class index for classification.
   */
  values: Array<number>;
  /**
   * Class order is 0..K. Binary models return [P(0), P(1)].
   */
  probabilities: Array<Array<number>> | null;
};
