// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentDocument = {
  title: string;
  path: string;
  /**
   * See `TutorialDocument::readable`: a stored macOS TCC deny leaves a
   * real file on disk that opening it still refuses.
   */
  readable: boolean;
};
