// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericPrecision } from "./NumericPrecision";
import type { Step } from "./Step";

/**
 * Steps are in topological order, while named slots permit independent
 * branches. `features` is the final matrix order, not the order inputs happened
 * to arrive in. This is sufficient to describe the first ColumnTransformer
 * examples without inventing a separate mutable frame for each fitted step.
 */
export type Recipe = {
  precision: NumericPrecision;
  steps: Array<Step>;
  features: Array<string>;
};
