// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameJoin } from "./FrameJoin";

/**
 * That this frame is derived, and from what.
 *
 * Deliberately thin: a derivation's chain travels as `ComputedFrame::steps`
 * like any other chain, so what is left here is the pair of facts the steps
 * do not carry — the frame the chain starts from, and the join, which is
 * held flat on `FrameDerivation` rather than as a step.
 */
export type RenderedFrameDerivation = {
  sourceFrameId: string;
  join: FrameJoin | null;
};
