// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedSort } from "./DerivedSort";
import type { ExpandOutput } from "./ExpandOutput";
import type { FrameJoin } from "./FrameJoin";
import type { PivotAggregate } from "./PivotAggregate";
import type { PivotOutput } from "./PivotOutput";
import type { RenderedDerivedExpression } from "./RenderedDerivedExpression";
import type { UnionColumn } from "./UnionColumn";
import type { UnpivotColumn } from "./UnpivotColumn";

export type RenderedFrameStep =
  | { "kind": "filter"; predicates: Array<string>; matchAll: boolean }
  | { "kind": "withColumns"; columns: Array<RenderedDerivedExpression> }
  | { "kind": "select"; columnIds: Array<string> }
  | {
    "kind": "summarize";
    groupKeys: Array<RenderedDerivedExpression>;
    aggregates: Array<RenderedDerivedExpression>;
    maintainOrder: boolean;
  }
  | { "kind": "join"; join: FrameJoin }
  | { "kind": "sort"; keys: Array<DerivedSort> }
  | { "kind": "union"; frameId: string; mapping: Array<UnionColumn> }
  | { "kind": "expand"; frameId: string; outputs: Array<ExpandOutput> }
  | {
    "kind": "pivot";
    namesColumnId: string;
    valuesColumnId: string;
    aggregate: PivotAggregate;
    outputs: Array<PivotOutput>;
  }
  | {
    "kind": "unpivot";
    columns: Array<UnpivotColumn>;
    nameColumnId: string;
    nameColumnName: string;
    valueColumnId: string;
    valueColumnName: string;
  }
  | { "kind": "comment"; text: string };
