// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

/**
 * A value the document works out rather than one somebody typed.
 *
 * A value is static: a number, a date, a name, entered and then true until
 * somebody retypes it. A result is the other thing a single cell can be —
 * `= DownPayment / PurchasePrice` — and it holds the formula, not the
 * answer. The answer is computed when the document is read, from whatever
 * the formula's references hold *now*, which is what makes the card live
 * rather than a copy that quietly goes stale.
 *
 * The formula is stored parsed, the way a column's is: references travel
 * by id, so renaming a value does not orphan the results that read it.
 * What the formula may name is the scalar scope — values, lists, other
 * results, and columns of materialized frames — and never the columns of
 * "the current frame", because a result does not sit in one.
 */
export type ResultObject = { id: string; name: string; formula: Formula };
