// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";

export type Row = { id: string; cells: { [key in string]: Cell } };
