// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One matching cell in a frame read through pages.
 */
export type RowHit = {
  /**
   * Where the row sits in the frame *as displayed* — what the grid scrolls
   * to. Not the stored ordinal, which a display sort reorders away from.
   *
   * Typed for TypeScript rather than left to ts-rs, which renders a `u64`
   * as `bigint`: serde_json writes this as a plain JSON number, the same
   * reasoning `DocumentView::revision` carries.
   */
  rowIndex: number;
  /**
   * The row's identity, spelled by exactly the code a page read spells it
   * with, so a hit and the page the grid loads for it agree about which row
   * this is. For a frame that owns its rows that is the stored row's id;
   * for one read out of a file it is positional, which is all such a row
   * has ever had. `None` only when the plan gave back fewer identities than
   * rows, which nothing currently does.
   */
  rowId: string | null;
  columnId: string;
  /**
   * The matching cell's text, as displayed by `.cast(String)`.
   */
  snippet: string;
};
