// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaleOperation } from "./ScaleOperation";

export type ScaleParameters = {
  offset: number;
  /**
   * Retain the original operator as well as its parameter. Replacing an
   * ONNX f32 multiplier by its reciprocal divisor can change rounding; the
   * model should not change arithmetic merely to normalize a field name.
   */
  scale: number;
  operation: ScaleOperation;
};
