// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScalarValue =
  | { "type": "null" }
  | { "type": "number"; "value": number }
  | { "type": "string"; "value": string }
  | { "type": "boolean"; "value": boolean }
  | { "type": "date"; "value": string };
