// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named set of value-object values the document can be switched into.
 *
 * The spreadsheet answer to "what if the rate were 6%" is a second copy of
 * the workbook, and the third copy is where the model and its assumptions
 * stop agreeing. Here the assumptions stay one set of named objects and the
 * scenario carries only what it *disagrees* about: a value not mentioned
 * keeps the number somebody typed on its card, so adding an assumption to
 * the model does not mean revisiting three scenarios to give it a value.
 *
 * Stored as `value object id → raw literal`, in the value's own data type
 * and in the same spelling the card would hold, because that is what
 * evaluation reads. Keying by id rather than by name means renaming a value
 * changes nothing here, exactly as it changes nothing in a formula.
 */
export type Scenario = {
  id: string;
  name: string;
  /**
   * The values this scenario disagrees with the base about. A value
   * missing from the map is not "unset" — it is agreed, and reads its
   * own `raw`.
   */
  values: { [key in string]: string };
};
