// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";

/**
 * What a refresh or a repoint did to a frame's schema, in the words the
 * person reading it uses: column display names, not ids.
 *
 * Deliberately not stored. History records the columns a refresh produced,
 * which is the durable fact; *how they differ from the ones before* is a
 * sentence about one moment, useful when the refresh lands and misleading
 * forever after — a document reopened next week would otherwise still be
 * announcing that Region arrived.
 */
export type SchemaDiff = {
  /**
   * Fields the source now supplies that it did not before.
   */
  added: Array<string>;
  /**
   * Columns dropped because their field went away and nothing read them.
   */
  removed: Array<string>;
  /**
   * Columns whose field went away but which something still reads, with
   * what reads them. These keep their id and show nulls rather than
   * disappearing out from under a formula.
   */
  keptMissing: Array<[string, string]>;
  /**
   * Columns the source still supplies under a different type.
   */
  typeChanged: Array<[string, DataType, DataType]>;
};
