// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";

/**
 * A named list, written down rather than computed.
 *
 * The third thing a document can hold, after a value and a frame, and it
 * exists because of the shape of question a spreadsheet answers by
 * selecting a range: the allowed currencies, the regions that count as
 * domestic, the thresholds. Those are lists, they are not frames, and
 * making a frame of one is a way of saying it that nobody means.
 *
 * Values are kept as raw text for the same reason a cell is — it is what
 * was typed, it diffs a line at a time, and one parser turns text into a
 * value everywhere in the document rather than each place inventing its
 * own.
 */
export type SeriesObject = {
  id: string;
  name: string;
  dataType: DataType;
  values: Array<string>;
};
