// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XgboostObjective } from "./XgboostObjective";

export type Settings = {
  objective: XgboostObjective;
  rounds: number;
  maxDepth: number;
  learningRate: number;
  minChildWeight: number;
  subsample: number;
  columnSubsample: number;
  l2Regularization: number;
  seed: number;
  threads: number;
};
