// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentView } from "./DocumentView";
import type { SnapshotRefreshFailure } from "./SnapshotRefreshFailure";

/**
 * What a document-wide refresh did, frame by frame.
 *
 * Named rather than counted because the interesting cases are the ones a
 * number cannot describe: three refreshed and one failed, or nothing
 * refreshed at all because the only stale snapshot sits under a broken one.
 */
export type SnapshotRefresh = {
  document: DocumentView;
  /**
   * The frames recomputed, in the order they were done.
   */
  refreshed: Array<string>;
  failures: Array<SnapshotRefreshFailure>;
};
