// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a top-level `solve` line reports beside its answer, so the gutter
 * can say how the number was reached and offer to make it real.
 */
export type SolveReport = {
  /**
   * The value object the search varied.
   */
  targetId: string;
  targetName: string;
  answer: number;
  /**
   * The answer as `SetValue` should receive it: rounded to twelve
   * significant digits, so applying `138.75` writes `138.75` and not the
   * last bit of bisection noise.
   */
  answerRaw: string;
  iterations: number;
  /**
   * The difference between the two sides at the answer.
   */
  residual: number;
  low: number;
  high: number;
  /**
   * Model evaluations spent, each a private copy of the document.
   */
  evaluations: number;
};
