// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsMethod } from "./StatsMethod";

export type StatsResult = {
  method: StatsMethod;
  estimate: number | null;
  standardError: number | null;
  statistic: number | null;
  degreesOfFreedom: number | null;
  pValue: number | null;
  confidenceLower: number | null;
  confidenceUpper: number | null;
  nX: number;
  nY: number | null;
  confidenceLevel: number;
  warnings: Array<string>;
};
