// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatsMethod } from "./StatsMethod";

export type StatsRequest = { method: StatsMethod; confidenceLevel: number };
