// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";

/**
 * The first few rows as they stand partway down a chain.
 *
 * Unlike the schema, this runs the query — bounded by `limit`, and with
 * the limit pushed into the plan, so a step over four million rows reads
 * what it needs rather than the lot. Still not free, which is why it is
 * fetched once when a step's preview is opened rather than on every
 * keystroke.
 */
export type StepSample = {
  frameId: string;
  /**
   * The step this shows the output of.
   */
  stepIndex: number;
  columns: Array<Column>;
  rows: Array<Array<string>>;
  /**
   * Whether the chain has more rows than were asked for. Not a count:
   * counting is a scan, and the point of a sample is not doing one.
   */
  truncated: boolean;
};
