// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Imputation } from "./Imputation";
import type { MissingValue } from "./MissingValue";
import type { Scalar } from "./Scalar";
import type { ScaleParameters } from "./ScaleParameters";
import type { UnknownCategory } from "./UnknownCategory";

export type Step = {
  "kind": "impute";
  input: string;
  output: string;
  strategy: Imputation;
  missing: MissingValue;
  learned: Scalar | null;
} | {
  "kind": "scale";
  input: string;
  output: string;
  learned: ScaleParameters | null;
} | {
  "kind": "oneHot";
  input: string;
  outputs: Array<string>;
  unknown: UnknownCategory;
  learned: Array<string> | null;
};
