// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";

/**
 * The columns visible after one step.
 */
export type StepSchema = { columns: Array<Column> };
