// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuggestionKind } from "./SuggestionKind";

export type Suggestion = {
  id: string;
  label: string;
  insertText: string;
  kind: SuggestionKind;
  detail: string;
  /**
   * A fuzzy-match score, which ts-rs would otherwise render as `bigint`
   * because the Rust side is 64-bit. It is a ranking number in the low
   * hundreds, and JSON carries it as an ordinary JavaScript number.
   */
  score: number;
  matchIndices?: Array<number>;
};
