// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummaryOperation } from "./SummaryOperation";

export type Summary = {
  id: string;
  columnId: string;
  operation: SummaryOperation;
  label: string;
};
