// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummaryOperation =
  | "sum"
  | "mean"
  | "quartile25"
  | "median"
  | "quartile75"
  | "min"
  | "max"
  | "count"
  | "missing"
  | "countDistinct"
  | "mode";
