// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Formula } from "./Formula";

/**
 * One piece of a text card, in order.
 */
export type TextSegment = { "kind": "literal"; text: string } | {
  "kind": "formula";
  formula: Formula;
} | { "kind": "broken"; source: string; error: string };
