// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextSegment } from "./TextSegment";

/**
 * A card of prose: markdown, with `{{…}}` holes where live values render.
 *
 * `segments` is the stored truth. The literal pieces keep the author's
 * markdown byte for byte; each hole keeps a parsed scalar formula, which
 * references the things it reads by id — so a rename elsewhere in the
 * document changes what the hole *prints* without anyone editing this
 * card. The editable source is reconstructed from the segments on every
 * view, the same way a chain renders its formulas back to text.
 *
 * `text` is the shape this object had before segments existed: one plain
 * string. It is read once, as a single literal, when `segments` is empty,
 * and cleared by the first real edit.
 */
export type TextObject = {
  id: string;
  name: string;
  text: string;
  segments?: Array<TextSegment>;
};
