// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workbook we ship for learning, copied into a visible Documents folder
 * only when the person asks for it. It deliberately has a path of its own,
 * rather than being a sample: the point of a tutorial is to change it.
 */
export type TutorialDocument = {
  title: string;
  lesson: string;
  kind: string;
  path: string;
  exists: boolean;
  /**
   * `exists` says the path is a file; this says FrameWork can actually
   * open it for reading. They diverge under macOS TCC: a stored Deny on
   * the Documents folder leaves a real file that opening still refuses.
   */
  readable: boolean;
};
