// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TutorialDocument } from "./TutorialDocument";

export type TutorialLibrary = {
  directory: string;
  documents: Array<TutorialDocument>;
};
