// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column an unpivot melts, with the display name its rows carry into
 * the name column.
 */
export type UnpivotColumn = { columnId: string; label: string };
