// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Twelve periods as calendar months, or as 4/5-week blocks repeating per
 * quarter: 4-4-5, 4-5-4, 5-4-4. A 53-week year extends the last period.
 */
export type WeekPattern =
  | "months"
  | "fourFourFive"
  | "fourFiveFour"
  | "fiveFourFour";
