// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IterationRange } from "./IterationRange";
import type { XgboostObjective } from "./XgboostObjective";
import type { XgboostTree } from "./XgboostTree";

export type XgboostModel = {
  featureNames: Array<string>;
  predictionRange: IterationRange | null;
  features: number;
  groups: number;
  objective: XgboostObjective;
  baseMargin: number;
  trees: Array<XgboostTree>;
  groupsByTree: Array<number>;
  iterations: Array<number>;
};
