// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type XgboostNode = { "kind": "leaf"; "data": number } | {
  "kind": "split";
  "data": {
    feature: number;
    threshold: number;
    left: number;
    right: number;
    default_left: boolean;
  };
};
