// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which calendar year a fiscal year is numbered with. A February-start
 * year running February 2025 to January 2026 is FY2025 by its start and
 * FY2026 by its end: the NRF labels its calendars by the start, most
 * companies and governments by the end. Relative answers — quarters,
 * weeks, year-to-date windows — never depend on this; only the year
 * number a date reports does.
 */
export type YearLabel = "start" | "end";
