// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a retail year ends. Calendar months end on their last day; a retail
 * year ends on a weekday the rule names: the last one of a month, or the
 * one nearest a month-day anchor. NRF 4-5-4 ends the Saturday nearest
 * January 31, which is what makes 2023 a 53-week year and 2024 a 52-week
 * one. Nearest cannot tie — two Saturdays are seven days apart, so one is
 * always strictly closer.
 */
export type YearEndRule = "lastDayOfMonth" | {
  "lastWeekday": { weekday: number };
} | { "nearestWeekday": { weekday: number; month: number; day: number } };
