// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One output column of a union: where the stacked frame's rows get their
 * value for `column_id`. `None` means the stacked frame had no column
 * with a matching name when the step was written, so its rows hold
 * nothing there.
 * How a paired list meets the rows.
 */
export type ZipFill = "exact" | "repeat";
